#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.local/share/Trash/ ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                hsetroot -fill "$file" ;;
        esac
done
