#!/bin/sh
# dmoji - dmenu based emoji picker

# GNU cut doesn't grok UTF-8.
EMOJI=$(sed '1,/^exit/d' $0 | dmenu -i -l 10 -fn 'Iosevka Term':size=11 | /usr/bin/grep -Po '^.')
if [ "$EMOJI" ]; then
	printf %s "$EMOJI" | xclip -i
	sleep 0.1
	xdotool click 2
	exit $?
fi
exit 1
😀  GRINNING FACE  #face #grin #person
😁  GRINNING FACE WITH SMILING EYES  #eye #face #grin #person #smile
😂  FACE WITH TEARS OF JOY  #face #joy #laugh #person #tear
😃  SMILING FACE WITH OPEN MOUTH  #face #mouth #open #person #smile
😄  SMILING FACE WITH OPEN MOUTH AND SMILING EYES  #eye #face #mouth #open #person #smile
😅  SMILING FACE WITH OPEN MOUTH AND COLD SWEAT  #cold #face #open #person #smile #sweat
😆  SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES  #face #laugh #mouth #open #person #satisfied #smile
😉  WINKING FACE  #face #person #wink
😊  SMILING FACE WITH SMILING EYES  #blush #eye #face #person #smile
😋  FACE SAVOURING DELICIOUS FOOD  #delicious #face #food #person #savouring #smile #um #yum
😎  SMILING FACE WITH SUNGLASSES  #bright #cool #eye #eyewear #face #glasses #person #smile #sun #sunglasses #weather
😍  SMILING FACE WITH HEART-SHAPED EYES  #eye #face #heart #love #person #smile
😘  FACE THROWING A KISS  #face #heart #kiss #person
😗  KISSING FACE  #face #kiss #person
😙  KISSING FACE WITH SMILING EYES  #eye #face #kiss #person #smile
😚  KISSING FACE WITH CLOSED EYES  #closed #eye #face #kiss #person
☺  WHITE SMILING FACE  #face #outlined #person #relaxed #smile
🙂  SLIGHTLY SMILING FACE  #face #person #smile
🤗  HUGGING FACE  #face #hug #hugging #person
😇  SMILING FACE WITH HALO  #angel #face #fairy_tale #fantasy #halo #innocent #person #smile
🤓  NERD FACE  #face #geek #nerd #person
🤔  THINKING FACE  #face #person #thinking
😐  NEUTRAL FACE  #deadpan #face #neutral #person
😑  EXPRESSIONLESS FACE  #expressionless #face #inexpressive #person #unexpressive
😶  FACE WITHOUT MOUTH	#face #mouth #person #quiet #silent
🙄  FACE WITH ROLLING EYES  #eyes #face #person #rolling
😏  SMIRKING FACE  #face #person #smirk
😣  PERSEVERING FACE  #face #persevere #person
😥  DISAPPOINTED BUT RELIEVED FACE  #disappointed #face #person #relieved #whew
😮  FACE WITH OPEN MOUTH  #face #mouth #open #person #sympathy
🤐  ZIPPER-MOUTH FACE  #face #mouth #person #zipper
😯  HUSHED FACE  #face #hushed #person #stunned #surprised
😪  SLEEPY FACE  #face #person #sleep
😫  TIRED FACE	#face #person #tired
😴  SLEEPING FACE  #face #person #sleep #zzz
😌  RELIEVED FACE  #face #person #relieved
😛  FACE WITH STUCK-OUT TONGUE	#face #person #tongue
😜  FACE WITH STUCK-OUT TONGUE AND WINKING EYE	#eye #face #joke #person #tongue #wink
😝  FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES	#eye #face #horrible #person #taste #tongue
😒  UNAMUSED FACE  #face #person #unamused #unhappy
😓  FACE WITH COLD SWEAT  #cold #face #person #sweat
😔  PENSIVE FACE  #dejected #face #pensive #person
😕  CONFUSED FACE  #confused #face #person
🙃  UPSIDE-DOWN FACE  #face #person #upside
🤑  MONEY-MOUTH FACE  #face #money #mouth #person
😲  ASTONISHED FACE  #astonished #face #person #shocked #totally
😷  FACE WITH MEDICAL MASK  #cold #doctor #face #mask #medicine #person #sick
🤒  FACE WITH THERMOMETER  #face #ill #person #sick #thermometer
🤕  FACE WITH HEAD-BANDAGE  #bandage #face #hurt #injury #person
☹  WHITE FROWNING FACE	#face #frown #person
🙁  SLIGHTLY FROWNING FACE  #face #frown #person
😖  CONFOUNDED FACE  #confounded #face #person
😞  DISAPPOINTED FACE  #disappointed #face #person
😟  WORRIED FACE  #face #person #worried
😤  FACE WITH LOOK OF TRIUMPH  #face #person #triumph #won
😢  CRYING FACE  #cry #face #person #sad #tear
😭  LOUDLY CRYING FACE	#cry #face #person #sad #sob #tear
😦  FROWNING FACE WITH OPEN MOUTH  #face #frown #mouth #open #person
😧  ANGUISHED FACE  #anguished #face #person
😨  FEARFUL FACE  #face #fear #fearful #person #scared
😩  WEARY FACE	#face #person #tired #weary
😬  GRIMACING FACE  #face #grimace #person
😰  FACE WITH OPEN MOUTH AND COLD SWEAT  #blue #cold #face #mouth #open #person #rushed #sweat
😱  FACE SCREAMING IN FEAR  #face #fear #fearful #munch #person #scared #scream
😳  FLUSHED FACE  #dazed #face #flushed #person
😵  DIZZY FACE	#dizzy #face #person
😡  POUTING FACE  #angry #face #mad #person #pouting #rage #red
😠  ANGRY FACE	#angry #face #mad #person
😈  SMILING FACE WITH HORNS  #face #fairy_tale #fantasy #horns #person #smile
👿  IMP  #demon #devil #face #fairy_tale #fantasy #imp #person
👹  JAPANESE OGRE  #creature #face #fairy_tale #fantasy #japanese #monster #ogre #person
👺  JAPANESE GOBLIN  #creature #face #fairy_tale #fantasy #goblin #japanese #monster #person
💀  SKULL  #body #death #face #fairy_tale #monster #person #skull
☠  SKULL AND CROSSBONES  #body #crossbones #death #face #monster #person #skull
👻  GHOST  #creature #face #fairy_tale #fantasy #ghost #monster #person
👽  EXTRATERRESTRIAL ALIEN  #alien #creature #extraterrestrial #face #fairy_tale #fantasy #monster #nature #person #space #ufo
👾  ALIEN MONSTER  #alien #creature #extraterrestrial #face #fairy_tale #fantasy #monster #nature #person #space #ufo
🤖  ROBOT FACE  #face #monster #person #robot
💩  PILE OF POO  #comic #dung #face #monster #nature #object #poo #poop
😺  SMILING CAT FACE WITH OPEN MOUTH  #animal #cat #face #mouth #nature #open #smile
😸  GRINNING CAT FACE WITH SMILING EYES  #animal #cat #eye #face #grin #nature #smile
😹  CAT FACE WITH TEARS OF JOY	#animal #cat #face #joy #nature #tear
😻  SMILING CAT FACE WITH HEART-SHAPED EYES  #animal #cat #eye #face #heart #love #nature #smile
😼  CAT FACE WITH WRY SMILE  #animal #cat #face #ironic #nature #smile #wry
😽  KISSING CAT FACE WITH CLOSED EYES  #animal #cat #eye #face #kiss #nature
🙀  WEARY CAT FACE  #animal #cat #face #nature #oh #surprised #weary
😿  CRYING CAT FACE  #animal #cat #cry #face #nature #sad #tear
😾  POUTING CAT FACE  #animal #cat #face #nature #pouting
🙈  SEE-NO-EVIL MONKEY	#animal #evil #face #forbidden #gesture #monkey #nature #no #not #prohibited #see
🙉  HEAR-NO-EVIL MONKEY  #animal #evil #face #forbidden #gesture #hear #monkey #nature #no #not #prohibited
🙊  SPEAK-NO-EVIL MONKEY  #animal #evil #face #forbidden #gesture #monkey #nature #no #not #prohibited #speak
👦  BOY  #boy #person
👧  GIRL  #girl #maiden #person #virgin #virgo #zodiac
👨  MAN  #man #person
👩  WOMAN  #person #woman
👴  OLDER MAN  #man #old #person
👵  OLDER WOMAN  #old #person #woman
👶  BABY  #baby #person
👱  PERSON WITH BLOND HAIR  #blond #person
👮  POLICE OFFICER  #cop #officer #person #police
👲  MAN WITH GUA PI MAO  #gua_pi_mao #hat #man #person
👳  MAN WITH TURBAN  #man #person #turban
👷  CONSTRUCTION WORKER  #construction #hat #person #worker
⛑  HELMET WITH WHITE CROSS  #aid #cross #face #hat #helmet #person
👸  PRINCESS  #fairy_tale #fantasy #person #princess
💂  GUARDSMAN  #guard #guardsman #person
🕵  SLEUTH OR SPY  #detective #person #sleuth #spy
🎅  FATHER CHRISTMAS  #activity #celebration #christmas #fairy_tale #fantasy #father #person #santa
👰  BRIDE WITH VEIL  #bride #person #veil #wedding
👼  BABY ANGEL	#angel #baby #face #fairy_tale #fantasy #person
💆  FACE MASSAGE  #massage #person #salon
💇  HAIRCUT  #barber #beauty #haircut #parlor #person
🙍  PERSON FROWNING  #frown #gesture #person
🙎  PERSON WITH POUTING FACE  #gesture #person #pouting
🙅  FACE WITH NO GOOD GESTURE  #forbidden #gesture #hand #no #not #person #prohibited
🙆  FACE WITH OK GESTURE  #gesture #hand #ok #person
💁  INFORMATION DESK PERSON  #hand #help #information #person #sassy
🙋  HAPPY PERSON RAISING ONE HAND  #gesture #hand #happy #person #raised
🙇  PERSON BOWING DEEPLY  #apology #bow #gesture #person #sorry
🙌  PERSON RAISING BOTH HANDS IN CELEBRATION  #body #celebration #gesture #hand #hooray #person #raised
🙏  PERSON WITH FOLDED HANDS  #ask #body #bow #folded #gesture #hand #person #please #pray #thanks
🗣  SPEAKING HEAD IN SILHOUETTE	#face #head #person #silhouette #speak #speaking
👤  BUST IN SILHOUETTE	#bust #person #silhouette
👥  BUSTS IN SILHOUETTE  #bust #person #silhouette
🚶  PEDESTRIAN	#hike #pedestrian #person #walk #walking
🏃  RUNNER  #marathon #person #runner #running
👯  WOMAN WITH BUNNY EARS  #bunny #dancer #ear #girl #person #woman
💃  DANCER  #dancer #person
🕴  MAN IN BUSINESS SUIT LEVITATING  #business #man #person #suit
👫  MAN AND WOMAN HOLDING HANDS  #couple #hand #hold #man #person #woman
👬  TWO MEN HOLDING HANDS  #couple #gemini #hand #hold #man #person #twins #zodiac
👭  TWO WOMEN HOLDING HANDS  #couple #hand #hold #person #woman
💏  KISS  #couple #kiss #person #romance
👩  Kiss: WOMAN, MAN  #kiss #man #woman
👨  Kiss: MAN, MAN  #kiss #man
👩  Kiss: WOMAN, WOMAN	#kiss #woman
💑  COUPLE WITH HEART  #couple #heart #love #person #romance
👩  Couple with heart: WOMAN, MAN  #couple #man #woman
👨  Couple with heart: MAN, MAN  #couple #man
👩  Couple with heart: WOMAN, WOMAN  #couple #woman
👪  FAMILY  #child #family #father #mother #person
👨  Family: MAN, WOMAN, BOY  #boy #family #man #woman
👨  Family: MAN, WOMAN, GIRL  #family #girl #man #woman
👨  Family: MAN, WOMAN, GIRL, BOY  #boy #family #girl #man #woman
👨  Family: MAN, WOMAN, BOY, BOY  #boy #family #man #woman
👨  Family: MAN, WOMAN, GIRL, GIRL  #family #girl #man #woman
👨  Family: MAN, MAN, BOY  #boy #family #man
👨  Family: MAN, MAN, GIRL  #family #girl #man
👨  Family: MAN, MAN, GIRL, BOY  #boy #family #girl #man
👨  Family: MAN, MAN, BOY, BOY	#boy #family #man
👨  Family: MAN, MAN, GIRL, GIRL  #family #girl #man
👩  Family: WOMAN, WOMAN, BOY  #boy #family #woman
👩  Family: WOMAN, WOMAN, GIRL	#family #girl #woman
👩  Family: WOMAN, WOMAN, GIRL, BOY  #boy #family #girl #woman
👩  Family: WOMAN, WOMAN, BOY, BOY  #boy #family #woman
👩  Family: WOMAN, WOMAN, GIRL, GIRL  #family #girl #woman
🏻  EMOJI MODIFIER FITZPATRICK TYPE-1-2	#emoji_modifier #fitzpatrick #skin #symbol #tone
🏼  EMOJI MODIFIER FITZPATRICK TYPE-3  #emoji_modifier #fitzpatrick #skin #symbol #tone
🏽  EMOJI MODIFIER FITZPATRICK TYPE-4  #emoji_modifier #fitzpatrick #skin #symbol #tone
🏾  EMOJI MODIFIER FITZPATRICK TYPE-5  #emoji_modifier #fitzpatrick #skin #symbol #tone
🏿  EMOJI MODIFIER FITZPATRICK TYPE-6  #emoji_modifier #fitzpatrick #skin #symbol #tone
💪  FLEXED BICEPS  #biceps #body #comic #flex #muscle #person
👈  WHITE LEFT POINTING BACKHAND INDEX	#backhand #body #finger #hand #index #person #point
👉  WHITE RIGHT POINTING BACKHAND INDEX  #backhand #body #finger #hand #index #person #point
☝  WHITE UP POINTING INDEX  #body #finger #hand #index #person #point #up
👆  WHITE UP POINTING BACKHAND INDEX  #backhand #body #finger #hand #index #person #point #up
🖕  REVERSED HAND WITH MIDDLE FINGER EXTENDED  #body #finger #hand #middle_finger #person
👇  WHITE DOWN POINTING BACKHAND INDEX	#backhand #body #down #finger #hand #index #person #point
✌  VICTORY HAND  #body #hand #person #v #victory
🖖  RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS  #body #finger #hand #person #spock #vulcan
🤘  SIGN OF THE HORNS  #body #finger #hand #horns #person #rock
🖐  RAISED HAND WITH FINGERS SPLAYED  #body #finger #hand #person #splayed
✋  RAISED HAND	#body #hand #person
👌  OK HAND SIGN  #body #hand #ok #person
👍  THUMBS UP SIGN  #body #hand #person #thumb #thumbs_up #up
👎  THUMBS DOWN SIGN  #body #down #hand #person #thumb #thumbs_down
✊  RAISED FIST	#body #clenched #fist #hand #person #punch
👊  FISTED HAND SIGN  #body #clenched #fist #hand #person #punch
👋  WAVING HAND SIGN  #body #hand #person #wave #waving
👏  CLAPPING HANDS SIGN  #body #clap #hand #person
👐  OPEN HANDS SIGN  #body #hand #open #person
✍  WRITING HAND  #body #education #hand #person #write
💅  NAIL POLISH  #body #care #cosmetics #manicure #nail #person #polish
👂  EAR  #body #ear #person
👃  NOSE  #body #nose #person
👣  FOOTPRINTS	#body #clothing #footprint #person #print
👀  EYES  #body #eye #face #person
👁  EYE	#body #eye #person
👁  EYE, LEFT SPEECH BUBBLE  #bubble #eye #speech #witness
👅  TONGUE  #body #person #tongue
👄  MOUTH  #body #lips #mouth #person
💋  KISS MARK  #emotion #heart #kiss #lips #mark #person #romance
💘  HEART WITH ARROW  #arrow #cupid #emotion #heart #person #romance
❤  HEAVY BLACK HEART  #emotion #heart #person
💓  BEATING HEART  #beating #emotion #heart #heartbeat #person #pulsating
💔  BROKEN HEART  #break #broken #emotion #heart #person
💕  TWO HEARTS	#emotion #heart #love #person
💖  SPARKLING HEART  #emotion #excited #heart #person #sparkle
💗  GROWING HEART  #emotion #excited #growing #heart #heartpulse #nervous #person
💙  BLUE HEART	#blue #emotion #heart #person
💚  GREEN HEART  #emotion #green #heart #person
💛  YELLOW HEART  #emotion #heart #person #yellow
💜  PURPLE HEART  #emotion #heart #person #purple
💝  HEART WITH RIBBON  #emotion #heart #object #person #ribbon #valentine
💞  REVOLVING HEARTS  #emotion #heart #person #revolving
💟  HEART DECORATION  #emotion #heart #person #symbol
❣  HEAVY HEART EXCLAMATION MARK ORNAMENT  #emotion #exclamation #heart #mark #punctuation #symbol
💌  LOVE LETTER  #emotion #heart #letter #love #mail #person #romance
💤  SLEEPING SYMBOL  #comic #emotion #person #sleep #symbol #word #zzz
💢  ANGER SYMBOL  #angry #comic #emotion #mad #person #symbol
💣  BOMB  #bomb #comic #object
💥  COLLISION SYMBOL  #boom #collision #comic #emotion #person
💦  SPLASHING SWEAT SYMBOL  #comic #emotion #object #person #splashing #sweat
💨  DASH SYMBOL  #comic #dash #emotion #object #person #running
💫  DIZZY SYMBOL  #comic #dizzy #emotion #person #star
💬  SPEECH BALLOON  #balloon #bubble #comic #dialog #emotion #object #person #speech
🗨  LEFT SPEECH BUBBLE  #dialog #other #speech
🗯  RIGHT ANGER BUBBLE  #angry #balloon #bubble #emotion #mad #symbol
💭  THOUGHT BALLOON  #balloon #bubble #comic #emotion #object #person #thought
🕳  HOLE  #hole #symbol
👓  EYEGLASSES	#clothing #eye #eyeglasses #eyewear #glasses #object #person
🕶  DARK SUNGLASSES  #dark #eye #eyewear #glasses #object #sunglasses
👔  NECKTIE  #clothing #necktie #object #person
👕  T-SHIRT  #clothing #object #person #shirt #tshirt
👖  JEANS  #clothing #jeans #object #pants #person #trousers
👗  DRESS  #clothing #dress #object #person
👘  KIMONO  #clothing #kimono #object #person
👙  BIKINI  #bikini #clothing #object #person #swim
👚  WOMANS CLOTHES  #clothing #object #person #woman
👛  PURSE  #clothing #coin #object #person #purse
👜  HANDBAG  #bag #clothing #handbag #object #person
👝  POUCH  #bag #clothing #object #person #pouch
🛍  SHOPPING BAGS  #bag #hotel #object #shopping
🎒  SCHOOL SATCHEL  #activity #bag #education #object #satchel #school
👞  MANS SHOE  #clothing #man #object #person #shoe
👟  ATHLETIC SHOE  #athletic #clothing #object #person #shoe #sneaker
👠  HIGH-HEELED SHOE  #clothing #heel #object #person #shoe #woman
👡  WOMANS SANDAL  #clothing #object #person #sandal #shoe #woman
👢  WOMANS BOOTS  #boot #clothing #object #person #shoe #woman
👑  CROWN  #clothing #crown #king #object #person #queen
👒  WOMANS HAT	#clothing #hat #object #person #woman
🎩  TOP HAT  #activity #clothing #entertainment #hat #object #person #top #tophat
🎓  GRADUATION CAP  #activity #cap #celebration #clothing #education #graduation #hat #object
📿  PRAYER BEADS  #beads #clothing #necklace #object #person #prayer #religion
💄  LIPSTICK  #cosmetics #lipstick #makeup #object #person
💍  RING  #diamond #emotion #object #person #ring #romance
💎  GEM STONE  #diamond #emotion #gem #jewel #object #person #romance
🐵  MONKEY FACE  #animal #face #monkey #nature
🐒  MONKEY  #animal #monkey #nature
🐶  DOG FACE  #animal #dog #face #nature #pet
🐕  DOG  #animal #dog #nature #pet
🐩  POODLE  #animal #dog #nature #poodle
🐺  WOLF FACE  #animal #face #nature #wolf
🐱  CAT FACE  #animal #cat #face #nature #pet
🐈  CAT  #animal #cat #nature #pet
🦁  LION FACE  #animal #face #leo #lion #nature #zodiac
🐯  TIGER FACE	#animal #face #nature #tiger
🐅  TIGER  #animal #nature #tiger
🐆  LEOPARD  #animal #leopard #nature
🐴  HORSE FACE	#animal #face #horse #nature
🐎  HORSE  #animal #horse #nature #place #racehorse #racing
🦄  UNICORN FACE  #animal #face #nature #unicorn
🐮  COW FACE  #animal #cow #face #nature
🐂  OX	#animal #bull #nature #ox #taurus #zodiac
🐃  WATER BUFFALO  #animal #buffalo #nature #water
🐄  COW  #animal #cow #nature
🐷  PIG FACE  #animal #face #nature #pig
🐖  PIG  #animal #nature #pig #sow
🐗  BOAR  #animal #boar #nature #pig
🐽  PIG NOSE  #animal #face #nature #nose #pig
🐏  RAM  #animal #aries #nature #ram #sheep #zodiac
🐑  SHEEP  #animal #ewe #nature #sheep
🐐  GOAT  #animal #capricorn #goat #nature #zodiac
🐪  DROMEDARY CAMEL  #animal #camel #dromedary #hump #nature
🐫  BACTRIAN CAMEL  #animal #bactrian #camel #hump #nature
🐘  ELEPHANT  #animal #elephant #nature
🐭  MOUSE FACE	#animal #face #mouse #nature
🐁  MOUSE  #animal #mouse #nature
🐀  RAT  #animal #nature #rat
🐹  HAMSTER FACE  #animal #face #hamster #nature #pet
🐰  RABBIT FACE  #animal #bunny #face #nature #pet #rabbit
🐇  RABBIT  #animal #bunny #nature #pet #rabbit
🐿  CHIPMUNK  #animal #chipmunk #nature
🐻  BEAR FACE  #animal #bear #face #nature
🐨  KOALA  #animal #bear #koala #nature
🐼  PANDA FACE	#animal #face #nature #panda
🐾  PAW PRINTS	#animal #feet #nature #paw #print
🦃  TURKEY  #animal #nature #turkey
🐔  CHICKEN  #animal #chicken #nature
🐓  ROOSTER  #animal #nature #rooster
🐣  HATCHING CHICK  #animal #baby #chick #hatching #nature
🐤  BABY CHICK	#animal #baby #chick #nature
🐥  FRONT-FACING BABY CHICK  #animal #baby #chick #nature
🐦  BIRD  #animal #bird #nature
🐧  PENGUIN  #animal #nature #penguin
🕊  DOVE OF PEACE  #animal #bird #dove #fly #nature #peace
🐸  FROG FACE  #animal #face #frog #nature
🐊  CROCODILE  #animal #crocodile #nature
🐢  TURTLE  #animal #nature #turtle
🐍  SNAKE  #animal #bearer #nature #ophiuchus #serpent #snake #zodiac
🐲  DRAGON FACE  #animal #dragon #face #fairy_tale #nature
🐉  DRAGON  #animal #dragon #fairy_tale #nature
🐳  SPOUTING WHALE  #animal #face #nature #spouting #whale
🐋  WHALE  #animal #nature #whale
🐬  DOLPHIN  #animal #dolphin #flipper #nature
🐟  FISH  #animal #fish #nature #pisces #zodiac
🐠  TROPICAL FISH  #animal #fish #nature #tropical
🐡  BLOWFISH  #animal #blowfish #fish #nature
🐙  OCTOPUS  #animal #nature #octopus
🐚  SPIRAL SHELL  #animal #nature #shell #spiral
🦀  CRAB  #animal #cancer #crab #nature #zodiac
🐌  SNAIL  #animal #nature #snail
🐛  BUG  #animal #bug #insect #nature
🐜  ANT  #animal #ant #insect #nature
🐝  HONEYBEE  #animal #bee #honeybee #insect #nature
🐞  LADY BEETLE  #animal #beetle #insect #lady_beetle #ladybird #ladybug #nature
🕷  SPIDER  #animal #insect #object #spider
🕸  SPIDER WEB  #animal #object #spider #web
🦂  SCORPION  #animal #nature #scorpio #scorpion #scorpius #zodiac
💐  BOUQUET  #bouquet #flower #nature #object #place #plant #romance
🌸  CHERRY BLOSSOM  #blossom #cherry #flower #nature #plant
💮  WHITE FLOWER  #flower #object #symbol
🏵  ROSETTE  #nature #plant #rosette
🌹  ROSE  #flower #nature #plant #rose
🌺  HIBISCUS  #flower #hibiscus #nature #plant
🌻  SUNFLOWER  #flower #nature #plant #sun #sunflower
🌼  BLOSSOM  #blossom #flower #nature #plant
🌷  TULIP  #flower #nature #plant #tulip
🌱  SEEDLING  #nature #plant #seedling #young
🌲  EVERGREEN TREE  #evergreen #nature #plant #tree
🌳  DECIDUOUS TREE  #deciduous #nature #plant #shedding #tree
🌴  PALM TREE  #nature #palm #plant #tree
🌵  CACTUS  #cactus #nature #plant
🌾  EAR OF RICE  #ear #nature #plant #rice
🌿  HERB  #herb #leaf #nature #plant
☘  SHAMROCK  #nature #plant #shamrock
🍀  FOUR LEAF CLOVER  #4 #clover #four #leaf #nature #plant
🍁  MAPLE LEAF	#falling #leaf #maple #nature #plant
🍂  FALLEN LEAF  #falling #leaf #nature #plant
🍃  LEAF FLUTTERING IN WIND  #blow #flutter #leaf #nature #plant #wind
🍇  GRAPES  #food #fruit #grape #nature #object #plant
🍈  MELON  #food #fruit #melon #nature #object #plant
🍉  WATERMELON	#food #fruit #nature #object #plant #watermelon
🍊  TANGERINE  #food #fruit #nature #object #orange #plant #tangerine
🍋  LEMON  #citrus #food #fruit #lemon #nature #object #plant
🍌  BANANA  #banana #food #fruit #nature #object #plant
🍍  PINEAPPLE  #food #fruit #nature #object #pineapple #plant
🍎  RED APPLE  #apple #food #fruit #nature #object #plant #red
🍏  GREEN APPLE  #apple #food #fruit #green #nature #object #plant
🍐  PEAR  #food #fruit #nature #object #pear #plant
🍑  PEACH  #food #fruit #nature #object #peach #plant
🍒  CHERRIES  #cherry #food #fruit #nature #object #plant
🍓  STRAWBERRY	#berry #food #fruit #nature #object #plant #strawberry
🍅  TOMATO  #food #nature #object #plant #tomato #vegetable
🍆  AUBERGINE  #aubergine #eggplant #food #nature #object #plant #vegetable
🌽  EAR OF MAIZE  #corn #ear #maize #maze #nature #object #plant
🌶  HOT PEPPER  #food #hot #nature #pepper #plant
🍄  MUSHROOM  #mushroom #nature #plant
🌰  CHESTNUT  #chestnut #nature #plant
🍞  BREAD  #bread #food #loaf #nature #object
🧀  CHEESE WEDGE  #cheese #food #nature
🍖  MEAT ON BONE  #bone #food #meat #nature #object
🍗  POULTRY LEG  #bone #chicken #food #leg #nature #object #poultry
🍔  HAMBURGER  #burger #food #hamburger #nature #object
🍟  FRENCH FRIES  #food #french #fries #nature #object
🍕  SLICE OF PIZZA  #cheese #food #nature #object #pizza #slice
🌭  HOT DOG  #food #frankfurter #hot_dog #hotdog #nature #sausage
🌮  TACO  #food #mexican #nature #taco
🌯  BURRITO  #burrito #food #mexican #nature
🍳  COOKING  #cooking #egg #food #frying #nature #object #pan
🍲  POT OF FOOD  #food #nature #object #pot #stew
🍿  POPCORN  #food #nature #popcorn
🍱  BENTO BOX  #bento #box #food #nature #object
🍘  RICE CRACKER  #cracker #food #nature #object #rice
🍙  RICE BALL  #ball #food #japanese #nature #object #rice
🍚  COOKED RICE  #cooked #food #nature #object #rice
🍛  CURRY AND RICE  #curry #food #nature #object #rice
🍜  STEAMING BOWL  #bowl #food #nature #noodle #object #ramen #steaming
🍝  SPAGHETTI  #food #nature #object #pasta #spaghetti
🍠  ROASTED SWEET POTATO  #food #nature #object #potato #roasted #sweet
🍢  ODEN  #food #kebab #nature #object #oden #seafood #skewer #stick
🍣  SUSHI  #food #nature #object #sushi
🍤  FRIED SHRIMP  #food #fried #nature #object #prawn #shrimp #tempura
🍥  FISH CAKE WITH SWIRL DESIGN  #cake #fish #food #nature #object #pastry #swirl
🍡  DANGO  #dango #dessert #food #japanese #nature #object #skewer #stick #sweet
🍦  SOFT ICE CREAM  #cream #dessert #food #ice #icecream #nature #object #soft #sweet
🍧  SHAVED ICE	#dessert #food #ice #nature #object #shaved #sweet
🍨  ICE CREAM  #cream #dessert #food #ice #nature #object #sweet
🍩  DOUGHNUT  #dessert #donut #doughnut #food #nature #object #sweet
🍪  COOKIE  #cookie #dessert #food #nature #object #sweet
🎂  BIRTHDAY CAKE  #birthday #cake #celebration #dessert #food #object #pastry #sweet
🍰  SHORTCAKE  #cake #dessert #food #nature #object #pastry #shortcake #slice #sweet
🍫  CHOCOLATE BAR  #bar #chocolate #dessert #food #nature #object #sweet
🍬  CANDY  #candy #dessert #food #nature #object #sweet
🍭  LOLLIPOP  #candy #dessert #food #lollipop #nature #object #sweet
🍮  CUSTARD  #custard #dessert #food #nature #object #pudding #sweet
🍯  HONEY POT  #food #honey #honeypot #nature #object #pot #sweet
🍼  BABY BOTTLE  #baby #bottle #drink #milk #nature #object
☕  HOT BEVERAGE  #beverage #coffee #drink #hot #nature #object #steaming #tea
🍵  TEACUP WITHOUT HANDLE  #beverage #cup #drink #nature #object #tea #teacup
🍶  SAKE BOTTLE AND CUP  #bar #beverage #bottle #cup #drink #nature #object #sake
🍾  BOTTLE WITH POPPING CORK  #bar #bottle #cork #drink #nature #popping
🍷  WINE GLASS	#bar #beverage #drink #glass #nature #object #wine
🍸  COCKTAIL GLASS  #bar #cocktail #drink #glass #nature #object
🍹  TROPICAL DRINK  #bar #drink #nature #object #tropical
🍺  BEER MUG  #bar #beer #drink #mug #nature #object
🍻  CLINKING BEER MUGS	#bar #beer #clink #drink #mug #nature #object
🍽  FORK AND KNIFE WITH PLATE  #cooking #food #fork #knife #object #place #plate
🍴  FORK AND KNIFE  #cooking #food #fork #knife #nature #object
🔪  HOCHO  #cooking #hocho #knife #object #tool #weapon
🏺  AMPHORA  #amphora #aquarius #cooking #drink #jug #nature #tool #weapon #zodiac
🌍  EARTH GLOBE EUROPE-AFRICA  #africa #earth #europe #globe #nature #place #world
🌎  EARTH GLOBE AMERICAS  #americas #earth #globe #nature #place #world
🌏  EARTH GLOBE ASIA-AUSTRALIA	#asia #australia #earth #globe #nature #place #world
🌐  GLOBE WITH MERIDIANS  #earth #globe #meridians #nature #place #world
🗺  WORLD MAP  #map #place #world
🗾  SILHOUETTE OF JAPAN  #japan #map #place
🏔  SNOW CAPPED MOUNTAIN  #cold #mountain #nature #place #snow
⛰  MOUNTAIN  #mountain #place
🌋  VOLCANO  #eruption #mountain #nature #place #volcano #weather
🗻  MOUNT FUJI	#fuji #mountain #nature #place
🏕  CAMPING  #camping #nature #place
🏖  BEACH WITH UMBRELLA	#beach #nature #place #umbrella
🏜  DESERT  #desert #nature #place
🏝  DESERT ISLAND  #desert #island #nature #place
🏞  NATIONAL PARK  #national_park #nature #park #place
🏟  STADIUM  #place #stadium
🏛  CLASSICAL BUILDING  #building #classical #place
🏗  BUILDING CONSTRUCTION  #building #construction #place
🏘  HOUSE BUILDINGS  #building #house #place
🏙  CITYSCAPE  #building #city #place
🏚  DERELICT HOUSE BUILDING  #building #derelict #house #place
🏠  HOUSE BUILDING  #building #home #house #place
🏡  HOUSE WITH GARDEN  #building #garden #home #house #place
🏢  OFFICE BUILDING  #building #office #place
🏣  JAPANESE POST OFFICE  #building #japanese #office #place #post
🏤  EUROPEAN POST OFFICE  #building #european #office #place #post
🏥  HOSPITAL  #building #doctor #hospital #medicine #place
🏦  BANK  #bank #building #place
🏨  HOTEL  #building #hotel #place
🏩  LOVE HOTEL	#building #hotel #love #place
🏪  CONVENIENCE STORE  #building #convenience #place #store
🏫  SCHOOL  #building #education #place #school
🏬  DEPARTMENT STORE  #building #department #place #store
🏭  FACTORY  #building #factory #place
🏯  JAPANESE CASTLE  #building #castle #japanese #place
🏰  EUROPEAN CASTLE  #building #castle #european #place
💒  WEDDING  #activity #chapel #place #romance #wedding
🗼  TOKYO TOWER  #place #tokyo #tower
🗽  STATUE OF LIBERTY  #liberty #place #statue
⛪  CHURCH  #building #christian #church #cross #place #religion
🕌  MOSQUE  #islam #mosque #muslim #place #religion
🕍  SYNAGOGUE  #jew #jewish #place #religion #synagogue #temple
⛩  SHINTO SHRINE  #religion #shinto #shrine #symbol
🕋  KAABA  #islam #kaaba #muslim #place #religion
⛲  FOUNTAIN  #fountain #object #place
⛺  TENT  #camping #object #place #tent
🌁  FOGGY  #fog #nature #place #weather
🌃  NIGHT WITH STARS  #nature #night #place #star #weather
🌄  SUNRISE OVER MOUNTAINS  #morning #mountain #nature #place #sun #sunrise #time #weather
🌅  SUNRISE  #morning #nature #place #sun #sunrise #time #weather
🌆  CITYSCAPE AT DUSK  #building #city #dusk #evening #landscape #nature #place #sun #sunset #time #weather
🌇  SUNSET OVER BUILDINGS  #building #dusk #nature #place #sun #sunset #time #weather
🌉  BRIDGE AT NIGHT  #bridge #nature #night #place #weather
♨  HOT SPRINGS	#hot #hotsprings #place #springs #steaming
🌌  MILKY WAY  #milky_way #nature #place #space #weather
🎠  CAROUSEL HORSE  #activity #carousel #entertainment #horse #place
🎡  FERRIS WHEEL  #activity #amusement_park #entertainment #ferris #place #wheel
🎢  ROLLER COASTER  #activity #amusement_park #coaster #entertainment #place #roller
💈  BARBER POLE  #barber #haircut #place #pole
🎪  CIRCUS TENT  #activity #circus #entertainment #place #tent
🎭  PERFORMING ARTS  #activity #art #entertainment #mask #object #performing #place #theater #theatre
🖼  FRAME WITH PICTURE  #art #frame #museum #object #office #painting #picture
🎨  ARTIST PALETTE  #activity #art #entertainment #museum #object #painting #palette
🎰  SLOT MACHINE  #activity #game #object #place #slot
🚂  STEAM LOCOMOTIVE  #engine #locomotive #place #railway #steam #train #travel #vehicle
🚃  RAILWAY CAR  #car #electric #place #railway #train #tram #travel #trolleybus #vehicle
🚄  HIGH-SPEED TRAIN  #place #railway #shinkansen #speed #train #travel #vehicle
🚅  HIGH-SPEED TRAIN WITH BULLET NOSE  #bullet #place #railway #shinkansen #speed #train #travel #vehicle
🚆  TRAIN  #place #railway #train #travel #vehicle
🚇  METRO  #metro #place #subway #travel #vehicle
🚈  LIGHT RAIL	#place #railway #travel #vehicle
🚉  STATION  #place #railway #station #train #travel #vehicle
🚊  TRAM  #place #tram #travel #trolleybus #vehicle
🚝  MONORAIL  #monorail #place #travel #vehicle
🚞  MOUNTAIN RAILWAY  #car #mountain #place #railway #travel #vehicle
🚋  TRAM CAR  #car #place #tram #travel #trolleybus #vehicle
🚌  BUS  #bus #place #travel #vehicle
🚍  ONCOMING BUS  #bus #oncoming #place #travel #vehicle
🚎  TROLLEYBUS	#bus #place #tram #travel #trolley #trolleybus #vehicle
🚏  BUS STOP  #bus #busstop #place #stop #travel
🚐  MINIBUS  #bus #minibus #place #travel #vehicle
🚑  AMBULANCE  #ambulance #place #travel #vehicle
🚒  FIRE ENGINE  #engine #fire #place #travel #truck #vehicle
🚓  POLICE CAR	#car #patrol #place #police #travel #vehicle
🚔  ONCOMING POLICE CAR  #car #oncoming #place #police #travel #vehicle
🚕  TAXI  #place #taxi #travel #vehicle
🚖  ONCOMING TAXI  #oncoming #place #taxi #travel #vehicle
🚗  AUTOMOBILE	#automobile #car #place #travel #vehicle
🚘  ONCOMING AUTOMOBILE  #automobile #car #oncoming #place #travel #vehicle
🚙  RECREATIONAL VEHICLE  #place #recreational #rv #travel #vehicle
🚚  DELIVERY TRUCK  #delivery #place #travel #truck #vehicle
🚛  ARTICULATED LORRY  #lorry #place #semi #travel #truck #vehicle
🚜  TRACTOR  #place #tractor #travel #vehicle
🚲  BICYCLE  #bicycle #bike #place #sport #travel #vehicle
⛽  FUEL PUMP  #fuel #fuelpump #gas #place #pump #station #travel
🛣  MOTORWAY  #highway #motorway #place #road #travel
🛤  RAILWAY TRACK  #place #railway #train #travel
🚨  POLICE CARS REVOLVING LIGHT  #beacon #car #light #place #police #revolving #travel #vehicle
🚥  HORIZONTAL TRAFFIC LIGHT  #light #place #signal #traffic #travel
🚦  VERTICAL TRAFFIC LIGHT  #light #place #signal #traffic #travel
🚧  CONSTRUCTION SIGN  #barrier #construction #place #travel
⚓  ANCHOR  #anchor #place #ship #tool #travel
⛵  SAILBOAT  #boat #place #resort #sailboat #sea #travel #vehicle #yacht
🚣  ROWBOAT  #boat #place #rowboat #travel #vehicle
🚤  SPEEDBOAT  #boat #place #speedboat #travel #vehicle
🛳  PASSENGER SHIP  #passenger #place #ship #travel #vehicle
⛴  FERRY  #boat #ferry #place #travel
🛥  MOTOR BOAT  #boat #motorboat #place #travel #vehicle
🚢  SHIP  #place #ship #travel #vehicle
✈  AIRPLANE  #airplane #place #travel #vehicle
🛩  SMALL AIRPLANE  #airplane #place #travel #vehicle
🛫  AIRPLANE DEPARTURE  #airplane #check #departure #departures #place #travel #vehicle
🛬  AIRPLANE ARRIVING  #airplane #arrivals #arriving #landing #place #travel #vehicle
💺  SEAT  #chair #object #office #place #seat #travel
🚁  HELICOPTER	#helicopter #place #travel #vehicle
🚟  SUSPENSION RAILWAY	#place #railway #suspension #travel #vehicle
🚠  MOUNTAIN CABLEWAY  #cable #gondola #mountain #place #travel #vehicle
🚡  AERIAL TRAMWAY  #aerial #cable #car #gondola #place #ropeway #tramway #travel #vehicle
🚀  ROCKET  #place #rocket #space #travel #vehicle
🛰  SATELLITE  #place #satellite #space #vehicle
🛎  BELLHOP BELL  #bell #bellhop #hotel #object
🚪  DOOR  #door #object #travel
🛌  SLEEPING ACCOMMODATION  #hotel #object #sleep
🛏  BED	#bed #hotel #object #sleep
🛋  COUCH AND LAMP  #couch #hotel #lamp #object
🚽  TOILET  #object #place #toilet #travel
🚿  SHOWER  #object #place #shower #travel #water
🛀  BATH  #bath #bathtub #object #place #travel
🛁  BATHTUB  #bath #bathtub #object #place #travel
⌛  HOURGLASS  #hourglass #object #sand #time #timer
⏳  HOURGLASS WITH FLOWING SAND	#hourglass #object #sand #time #timer
⌚  WATCH  #clock #object #time #watch
⏰  ALARM CLOCK	#alarm #clock #object #time
⏱  STOPWATCH  #clock #object #stopwatch #time
⏲  TIMER CLOCK	#clock #object #time #timer
🕰  MANTELPIECE CLOCK  #clock #object
🕛  CLOCK FACE TWELVE OCLOCK  #00 #12 #12 #clock #o #symbol #time #twelve
🕧  CLOCK FACE TWELVE-THIRTY  #12 #12 #30 #clock #symbol #thirty #time #twelve
🕐  CLOCK FACE ONE OCLOCK  #00 #1 #1 #clock #o #one #symbol #time
🕜  CLOCK FACE ONE-THIRTY  #1 #1 #30 #clock #one #symbol #thirty #time
🕑  CLOCK FACE TWO OCLOCK  #00 #2 #2 #clock #o #symbol #time #two
🕝  CLOCK FACE TWO-THIRTY  #2 #2 #30 #clock #symbol #thirty #time #two
🕒  CLOCK FACE THREE OCLOCK  #00 #3 #3 #clock #o #symbol #three #time
🕞  CLOCK FACE THREE-THIRTY  #3 #3 #30 #clock #symbol #thirty #three #time
🕓  CLOCK FACE FOUR OCLOCK  #00 #4 #4 #clock #four #o #symbol #time
🕟  CLOCK FACE FOUR-THIRTY  #30 #4 #4 #clock #four #symbol #thirty #time
🕔  CLOCK FACE FIVE OCLOCK  #00 #5 #5 #clock #five #o #symbol #time
🕠  CLOCK FACE FIVE-THIRTY  #30 #5 #5 #clock #five #symbol #thirty #time
🕕  CLOCK FACE SIX OCLOCK  #00 #6 #6 #clock #o #six #symbol #time
🕡  CLOCK FACE SIX-THIRTY  #30 #6 #6 #clock #six #symbol #thirty #time
🕖  CLOCK FACE SEVEN OCLOCK  #00 #7 #7 #clock #o #seven #symbol #time
🕢  CLOCK FACE SEVEN-THIRTY  #30 #7 #7 #clock #seven #symbol #thirty #time
🕗  CLOCK FACE EIGHT OCLOCK  #00 #8 #8 #clock #eight #o #symbol #time
🕣  CLOCK FACE EIGHT-THIRTY  #30 #8 #8 #clock #eight #symbol #thirty #time
🕘  CLOCK FACE NINE OCLOCK  #00 #9 #9 #clock #nine #o #symbol #time
🕤  CLOCK FACE NINE-THIRTY  #30 #9 #9 #clock #nine #symbol #thirty #time
🕙  CLOCK FACE TEN OCLOCK  #00 #10 #10 #clock #o #symbol #ten #time
🕥  CLOCK FACE TEN-THIRTY  #10 #10 #30 #clock #symbol #ten #thirty #time
🕚  CLOCK FACE ELEVEN OCLOCK  #00 #11 #11 #clock #eleven #o #symbol #time
🕦  CLOCK FACE ELEVEN-THIRTY  #11 #11 #30 #clock #eleven #symbol #thirty #time
🌑  NEW MOON SYMBOL  #dark #moon #nature #place #space #time #weather
🌒  WAXING CRESCENT MOON SYMBOL  #crescent #moon #nature #place #space #time #waxing #weather
🌓  FIRST QUARTER MOON SYMBOL  #moon #nature #place #quarter #space #time #weather
🌔  WAXING GIBBOUS MOON SYMBOL	#gibbous #moon #nature #place #space #time #waxing #weather
🌕  FULL MOON SYMBOL  #full #moon #nature #place #space #time #weather
🌖  WANING GIBBOUS MOON SYMBOL	#gibbous #moon #nature #place #space #time #waning #weather
🌗  LAST QUARTER MOON SYMBOL  #moon #nature #place #quarter #space #time #weather
🌘  WANING CRESCENT MOON SYMBOL  #crescent #moon #nature #place #space #time #waning #weather
🌙  CRESCENT MOON  #crescent #moon #nature #place #space #time #weather
🌚  NEW MOON WITH FACE	#face #moon #nature #place #space #time #weather
🌛  FIRST QUARTER MOON WITH FACE  #face #moon #nature #place #quarter #space #weather
🌜  LAST QUARTER MOON WITH FACE  #face #moon #nature #place #quarter #space #weather
🌡  THERMOMETER	#nature #thermometer #weather
☀  BLACK SUN WITH RAYS	#bright #nature #rays #space #sun #sunny #weather
🌝  FULL MOON WITH FACE  #bright #face #full #moon #nature #place #space #weather
🌞  SUN WITH FACE  #bright #face #nature #place #space #sun #weather
⭐  WHITE MEDIUM STAR  #nature #place #star
🌟  GLOWING STAR  #glittery #glow #object #place #shining #sparkle #star
🌠  SHOOTING STAR  #activity #falling #nature #place #shooting #space #star
☁  CLOUD  #cloud #nature #weather
⛅  SUN BEHIND CLOUD  #cloud #nature #sun #weather
⛈  THUNDER CLOUD AND RAIN  #cloud #nature #rain #thunder #weather
🌤  WHITE SUN WITH SMALL CLOUD  #cloud #nature #sun #weather
🌥  WHITE SUN BEHIND CLOUD  #cloud #nature #sun #weather
🌦  WHITE SUN BEHIND CLOUD WITH RAIN  #cloud #nature #rain #sun #weather
🌧  CLOUD WITH RAIN  #cloud #nature #rain #weather
🌨  CLOUD WITH SNOW  #cloud #cold #nature #snow #weather
🌩  CLOUD WITH LIGHTNING  #cloud #lightning #nature #weather
🌪  CLOUD WITH TORNADO  #cloud #nature #tornado #weather #whirlwind
🌫  FOG	#cloud #fog #nature #weather
🌬  WIND BLOWING FACE  #blow #cloud #face #nature #weather #wind
🌀  CYCLONE  #cyclone #dizzy #nature #twister #typhoon #weather
🌈  RAINBOW  #nature #rain #rainbow #weather
🌂  CLOSED UMBRELLA  #clothing #nature #person #rain #umbrella #weather
☂  UMBRELLA  #clothing #nature #rain #umbrella #weather
☔  UMBRELLA WITH RAIN DROPS  #clothing #drop #nature #rain #umbrella #weather
⛱  UMBRELLA ON GROUND  #nature #rain #sun #travel #umbrella #weather
⚡  HIGH VOLTAGE SIGN  #danger #electric #electricity #lightning #nature #symbol #voltage #zap
❄  SNOWFLAKE  #cold #nature #snow #snowflake #weather
☃  SNOWMAN  #cold #nature #snow #snowman #weather
⛄  SNOWMAN WITHOUT SNOW  #cold #nature #snow #snowman #weather
☄  COMET  #comet #object #space
🔥  FIRE  #fire #flame #object #tool
💧  DROPLET  #cold #comic #drop #emotion #nature #object #person #sweat #weather
🌊  WATER WAVE	#nature #ocean #place #water #wave #weather
🎃  JACK-O-LANTERN  #activity #celebration #entertainment #halloween #jack #lantern #object
🎄  CHRISTMAS TREE  #activity #celebration #christmas #entertainment #object #tree
🎆  FIREWORKS  #activity #celebration #entertainment #fireworks #object
🎇  FIREWORK SPARKLER  #activity #celebration #entertainment #fireworks #object #sparkle
✨  SPARKLES  #emotion #entertainment #object #sign #sparkle #star
🎈  BALLOON  #activity #balloon #celebration #entertainment #object
🎉  PARTY POPPER  #activity #celebration #entertainment #object #party #popper #tada
🎊  CONFETTI BALL  #activity #ball #celebration #confetti #entertainment #object
🎋  TANABATA TREE  #activity #banner #celebration #entertainment #japanese #object #tree
🎍  PINE DECORATION  #activity #bamboo #celebration #japanese #object #pine #plant
🎎  JAPANESE DOLLS  #activity #celebration #doll #entertainment #festival #japanese #object
🎏  CARP STREAMER  #activity #carp #celebration #entertainment #flag #object #streamer
🎐  WIND CHIME	#activity #bell #celebration #chime #entertainment #object #wind
🎑  MOON VIEWING CEREMONY  #activity #celebration #ceremony #entertainment #moon #nature #object
🎀  RIBBON  #celebration #emotion #object #person #ribbon
🎁  WRAPPED PRESENT  #box #celebration #entertainment #gift #object #present #wrapped
🎗  REMINDER RIBBON  #celebration #object #reminder #ribbon
🎟  ADMISSION TICKETS  #admission #entertainment #object #ticket
🎫  TICKET  #activity #admission #entertainment #object #place #ticket
🎖  MILITARY MEDAL  #celebration #medal #military #object
🏆  TROPHY  #object #place #prize #sport #trophy
🏅  SPORTS MEDAL  #medal #object #sport
⚽  SOCCER BALL	#ball #object #place #soccer #sport
⚾  BASEBALL  #ball #baseball #object #place #sport
🏀  BASKETBALL AND HOOP  #ball #basketball #hoop #object #place #sport
🏐  VOLLEYBALL  #ball #game #object #sport #volleyball
🏈  AMERICAN FOOTBALL  #american #ball #football #object #place #sport
🏉  RUGBY FOOTBALL  #ball #football #object #place #rugby #sport
🎾  TENNIS RACQUET AND BALL  #ball #object #place #racquet #sport #tennis
🎱  BILLIARDS  #8 #8_ball #ball #billiard #eight #game #object #place #sport
🎳  BOWLING  #ball #bowling #game #object #place #sport
🏏  CRICKET BAT AND BALL  #ball #bat #cricket #game #object #sport
🏑  FIELD HOCKEY STICK AND BALL	#ball #field #game #hockey #object #sport #stick
🏒  ICE HOCKEY STICK AND PUCK  #game #hockey #ice #object #puck #sport #stick
🏓  TABLE TENNIS PADDLE AND BALL  #ball #bat #game #object #paddle #sport #table_tennis
🏸  BADMINTON RACQUET AND SHUTTLECOCK  #badminton #birdie #game #object #racquet #shuttlecock #sport
⛳  FLAG IN HOLE  #flag #golf #hole #object #place #sport #travel
🏌  GOLFER  #ball #golf #person #sport
⛸  ICE SKATE  #ice #place #skate #sport #travel
🎣  FISHING POLE AND FISH  #entertainment #fish #object #place #pole #sport
🎽  RUNNING SHIRT WITH SASH  #person #place #running #sash #shirt #sport
🎿  SKI AND SKI BOOT  #object #ski #snow #sport
⛷  SKIER  #person #ski #snow #sport #travel
🏂  SNOWBOARDER  #person #ski #snow #snowboard #sport
🏄  SURFER  #person #sport #surfer #surfing
🏇  HORSE RACING  #horse #jockey #person #racehorse #racing #sport #travel
🏊  SWIMMER  #person #sport #swim #swimmer #travel
⛹  PERSON WITH BALL  #ball #person #sport #travel
🏋  WEIGHT LIFTER  #lifter #person #sport #weight
🚴  BICYCLIST  #bicycle #bicyclist #bike #cyclist #person #place #sport #travel
🚵  MOUNTAIN BICYCLIST	#bicycle #bicyclist #bike #cyclist #mountain #person #place #sport #travel
🏎  RACING CAR  #car #place #racing #sport #travel
🏍  RACING MOTORCYCLE  #motorcycle #person #racing #sport #travel
🎯  DIRECT HIT	#activity #bull #bullseye #dart #entertainment #eye #game #hit #object #target
🎮  VIDEO GAME	#controller #entertainment #game #object #video_game
🕹  JOYSTICK  #entertainment #game #joystick #object #video_game
🎲  GAME DIE  #dice #die #entertainment #game #object
♠  BLACK SPADE SUIT  #card #game #spade #suit #symbol
♥  BLACK HEART SUIT  #card #emotion #game #heart #hearts #suit #symbol
♦  BLACK DIAMOND SUIT  #card #diamond #diamonds #game #suit #symbol
♣  BLACK CLUB SUIT  #card #club #clubs #game #suit #symbol
🃏  PLAYING CARD BLACK JOKER  #card #entertainment #game #joker #object #playing
🀄  MAHJONG TILE RED DRAGON  #game #mahjong #object #red
🎴  FLOWER PLAYING CARDS  #activity #card #entertainment #flower #game #japanese #object #playing
🔇  SPEAKER WITH CANCELLATION STROKE  #mute #object #quiet #silent #sound #speaker #volume
🔈  SPEAKER  #object #sound #speaker #volume
🔉  SPEAKER WITH ONE SOUND WAVE  #low #object #sound #speaker #volume #wave
🔊  SPEAKER WITH THREE SOUND WAVES  #3 #entertainment #high #loud #object #sound #speaker #three #volume
📢  PUBLIC ADDRESS LOUDSPEAKER	#communication #loud #loudspeaker #object #public_address #sound
📣  CHEERING MEGAPHONE	#cheering #communication #megaphone #object #sound
📯  POSTAL HORN  #communication #entertainment #horn #object #post #postal #sound
🔔  BELL  #bell #object #sound
🔕  BELL WITH CANCELLATION STROKE  #bell #forbidden #mute #no #not #object #prohibited #quiet #silent #sound
🎼  MUSICAL SCORE  #activity #entertainment #music #object #score #sound
🎵  MUSICAL NOTE  #activity #entertainment #music #note #object #sound
🎶  MULTIPLE MUSICAL NOTES  #activity #entertainment #music #note #notes #object #sound
🎙  STUDIO MICROPHONE  #mic #microphone #music #object #sound #studio
🎚  LEVEL SLIDER  #level #music #object #slider #sound
🎛  CONTROL KNOBS  #control #knobs #music #object #sound
🎤  MICROPHONE	#activity #entertainment #karaoke #mic #microphone #object #sound
🎧  HEADPHONE  #activity #earbud #entertainment #headphone #object #sound
📻  RADIO  #entertainment #object #radio #video
🎷  SAXOPHONE  #activity #entertainment #instrument #music #object #sax #saxophone #sound
🎸  GUITAR  #activity #entertainment #guitar #instrument #music #object #sound
🎹  MUSICAL KEYBOARD  #activity #entertainment #instrument #keyboard #music #object #piano #sound
🎺  TRUMPET  #activity #entertainment #instrument #music #object #sound #trumpet
🎻  VIOLIN  #activity #entertainment #instrument #music #object #sound #violin
📱  MOBILE PHONE  #cell #communication #mobile #object #phone #telephone
📲  MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT	#arrow #call #cell #communication #mobile #object #phone #receive #telephone
☎  BLACK TELEPHONE  #object #office #phone #sound #telephone
📞  TELEPHONE RECEIVER	#communication #object #phone #receiver #sound #telephone
📟  PAGER  #communication #object #office #pager
📠  FAX MACHINE  #communication #fax #object #office
🔋  BATTERY  #battery #object
🔌  ELECTRIC PLUG  #electric #electricity #object #plug
💻  PERSONAL COMPUTER  #computer #object #office #pc #personal
🖥  DESKTOP COMPUTER  #computer #desktop #object #office
🖨  PRINTER  #computer #object #office #printer
⌨  KEYBOARD  #computer #keyboard #object
🖱  THREE BUTTON MOUSE  #3 #button #computer #mouse #object #office #three
🖲  TRACKBALL  #computer #object #office #trackball
💽  MINIDISC  #computer #disk #entertainment #minidisk #object #office #optical
💾  FLOPPY DISK  #computer #disk #floppy #object #office
💿  OPTICAL DISC  #blu #cd #computer #disk #dvd #object #office #optical
📀  DVD  #blu #cd #computer #disk #dvd #entertainment #object #office #optical
🎥  MOVIE CAMERA  #activity #camera #cinema #entertainment #movie #object
🎞  FILM FRAMES	#cinema #entertainment #film #frames #movie #object
📽  FILM PROJECTOR  #cinema #entertainment #film #movie #object #projector #video
🎬  CLAPPER BOARD  #activity #clapper #entertainment #movie #object
📺  TELEVISION	#entertainment #object #television #tv #video
📷  CAMERA  #camera #entertainment #object #video
📸  CAMERA WITH FLASH  #camera #flash #object #video
📹  VIDEO CAMERA  #camera #entertainment #object #video
📼  VIDEOCASSETTE  #entertainment #object #tape #vhs #video #videocassette
🔍  LEFT-POINTING MAGNIFYING GLASS  #glass #magnifying #object #search #tool
🔎  RIGHT-POINTING MAGNIFYING GLASS  #glass #magnifying #object #search #tool
🔬  MICROSCOPE	#microscope #object #tool
🔭  TELESCOPE  #object #telescope #tool
📡  SATELLITE ANTENNA  #antenna #communication #dish #object #office #satellite
🕯  CANDLE  #candle #light #object
💡  ELECTRIC LIGHT BULB  #bulb #comic #electric #idea #light #object
🔦  ELECTRIC TORCH  #electric #flashlight #light #object #tool #torch
🏮  IZAKAYA LANTERN  #bar #japanese #lantern #light #place #red
📔  NOTEBOOK WITH DECORATIVE COVER  #book #cover #decorated #education #notebook #object #office
📕  CLOSED BOOK  #book #closed #education #object #office
📖  OPEN BOOK  #book #education #object #office #open
📗  GREEN BOOK	#book #education #green #object #office
📘  BLUE BOOK  #blue #book #education #object #office
📙  ORANGE BOOK  #book #education #object #office #orange
📚  BOOKS  #book #books #education #object #office
📓  NOTEBOOK  #notebook #object #office
📒  LEDGER  #ledger #notebook #object #office
📃  PAGE WITH CURL  #curl #document #object #office #page
📜  SCROLL  #object #office #paper #scroll
📄  PAGE FACING UP  #document #object #office #page
📰  NEWSPAPER  #communication #news #newspaper #object #paper
🗞  ROLLED-UP NEWSPAPER	#news #newspaper #object #paper #rolled
📑  BOOKMARK TABS  #bookmark #mark #marker #object #office #tabs
🔖  BOOKMARK  #bookmark #mark #object
🏷  LABEL  #label #object
💰  MONEY BAG  #bag #dollar #money #moneybag #object #office
💴  BANKNOTE WITH YEN SIGN  #bank #banknote #bill #currency #money #note #object #office #yen
💵  BANKNOTE WITH DOLLAR SIGN  #bank #banknote #bill #currency #dollar #money #note #object #office
💶  BANKNOTE WITH EURO SIGN  #bank #banknote #bill #currency #euro #money #note #object #office
💷  BANKNOTE WITH POUND SIGN  #bank #banknote #bill #currency #money #note #object #office #pound
💸  MONEY WITH WINGS  #bank #banknote #bill #dollar #fly #money #note #object #office #wings
💳  CREDIT CARD  #bank #card #credit #money #object #office
💹  CHART WITH UPWARDS TREND AND YEN SIGN  #bank #chart #currency #graph #growth #market #money #object #office #rise #symbol #trend #upward #yen
💱  CURRENCY EXCHANGE  #bank #currency #exchange #money #object #office #symbol
💲  HEAVY DOLLAR SIGN  #currency #dollar #money #object #office #symbol
✉  ENVELOPE  #e #email #envelope #object #office
📧  E-MAIL SYMBOL  #communication #e #email #letter #mail #object #office
📨  INCOMING ENVELOPE  #communication #e #email #envelope #incoming #letter #mail #object #office #receive
📩  ENVELOPE WITH DOWNWARDS ARROW ABOVE  #arrow #communication #down #e #email #envelope #letter #mail #object #office #outgoing #sent
📤  OUTBOX TRAY  #box #communication #letter #mail #object #office #outbox #sent #tray
📥  INBOX TRAY	#box #communication #inbox #letter #mail #object #office #receive #tray
📦  PACKAGE  #box #communication #object #office #package #parcel
📫  CLOSED MAILBOX WITH RAISED FLAG  #closed #communication #flag #mail #mailbox #object #office #postbox
📪  CLOSED MAILBOX WITH LOWERED FLAG  #closed #communication #flag #lowered #mail #mailbox #object #office #postbox
📬  OPEN MAILBOX WITH RAISED FLAG  #communication #flag #mail #mailbox #object #office #open #postbox
📭  OPEN MAILBOX WITH LOWERED FLAG  #communication #flag #lowered #mail #mailbox #object #office #open #postbox
📮  POSTBOX  #communication #mail #mailbox #object #office #postbox
🗳  BALLOT BOX WITH BALLOT  #ballot #box #object
✏  PENCIL  #object #office #pencil
✒  BLACK NIB  #nib #object #office #pen
🖋  LOWER LEFT FOUNTAIN PEN  #communication #fountain #object #office #pen
🖊  LOWER LEFT BALLPOINT PEN  #ballpoint #communication #object #office #pen
🖌  LOWER LEFT PAINTBRUSH  #communication #object #office #paintbrush #painting
🖍  LOWER LEFT CRAYON  #communication #crayon #object #office
📝  MEMO  #communication #memo #object #office #pencil
💼  BRIEFCASE  #briefcase #object #office #person
📁  FILE FOLDER  #file #folder #object #office
📂  OPEN FILE FOLDER  #file #folder #object #office #open
🗂  CARD INDEX DIVIDERS	#card #dividers #index #object #office
📅  CALENDAR  #calendar #date #object #office
📆  TEAR-OFF CALENDAR  #calendar #object #office
🗒  SPIRAL NOTE PAD  #note #object #office #pad #spiral
🗓  SPIRAL CALENDAR PAD	#calendar #object #office #pad #spiral
📇  CARD INDEX	#card #index #object #office #rolodex
📈  CHART WITH UPWARDS TREND  #chart #graph #growth #object #office #trend #upward
📉  CHART WITH DOWNWARDS TREND	#chart #down #graph #object #office #trend
📊  BAR CHART  #bar #chart #graph #object #office
📋  CLIPBOARD  #clipboard #object #office
📌  PUSHPIN  #object #office #pin #pushpin
📍  ROUND PUSHPIN  #object #office #pin #place #pushpin
📎  PAPERCLIP  #object #office #paperclip
🖇  LINKED PAPERCLIPS  #communication #link #object #office #paperclip
📏  STRAIGHT RULER  #object #office #ruler #straight_edge
📐  TRIANGULAR RULER  #object #office #ruler #set #triangle
✂  BLACK SCISSORS  #object #office #scissors #tool
🗃  CARD FILE BOX  #box #card #file #object #office
🗄  FILE CABINET  #cabinet #file #object #office
🗑  WASTEBASKET	#object #office #wastebasket
🔒  LOCK  #closed #lock #object
🔓  OPEN LOCK  #lock #object #open #unlock
🔏  LOCK WITH INK PEN  #ink #lock #nib #object #pen #privacy
🔐  CLOSED LOCK WITH KEY  #closed #key #lock #object #secure
🔑  KEY  #key #lock #object #password
🗝  OLD KEY  #clue #key #lock #object #old
🔨  HAMMER  #hammer #object #tool
⛏  PICK  #mining #object #pick #tool
⚒  HAMMER AND PICK  #hammer #object #pick #tool
🛠  HAMMER AND WRENCH  #hammer #object #tool #wrench
🗡  DAGGER KNIFE  #dagger #knife #object #weapon
⚔  CROSSED SWORDS  #crossed #object #swords #weapon
🔫  PISTOL  #gun #handgun #object #pistol #revolver #tool #weapon
🏹  BOW AND ARROW  #archer #arrow #bow #object #sagittarius #sport #tool #weapon #zodiac
🛡  SHIELD  #object #shield #weapon
🔧  WRENCH  #object #tool #wrench
🔩  NUT AND BOLT  #bolt #nut #object #tool
⚙  GEAR  #gear #object #tool
🗜  COMPRESSION	#compression #object #tool #vice
⚗  ALEMBIC  #alembic #chemistry #object #tool
⚖  SCALES  #balance #justice #libra #object #scales #tool #weight #zodiac
🔗  LINK SYMBOL  #link #object #symbol
⛓  CHAINS  #chain #object
💉  SYRINGE  #doctor #medicine #needle #object #shot #sick #syringe #tool
💊  PILL  #doctor #medicine #object #pill #sick
🚬  SMOKING SYMBOL  #activity #object #smoking
⚰  COFFIN  #coffin #death #object
⚱  FUNERAL URN	#death #funeral #object #urn
🗿  MOYAI  #face #moyai #place #statue #travel
🛢  OIL DRUM  #drum #object #oil
🔮  CRYSTAL BALL  #ball #crystal #fairy_tale #fantasy #fortune #object #tool
🏧  AUTOMATED TELLER MACHINE  #atm #automated #bank #place #sign #symbol #teller
🚮  PUT LITTER IN ITS PLACE SYMBOL  #litter #litterbox #place #symbol #travel
🚰  POTABLE WATER SYMBOL  #drink #potable #sign #symbol #travel #water
♿  WHEELCHAIR SYMBOL  #access #sign #symbol #travel #wheelchair
🚹  MENS SYMBOL  #lavatory #man #restroom #sign #symbol #travel #wc
🚺  WOMENS SYMBOL  #lavatory #restroom #sign #symbol #travel #wc #woman
🚻  RESTROOM  #lavatory #restroom #sign #symbol #travel #wc
🚼  BABY SYMBOL  #baby #changing #sign #symbol #travel
🚾  WATER CLOSET  #closet #lavatory #place #restroom #sign #symbol #travel #water #wc
🛂  PASSPORT CONTROL  #control #passport #place #sign #symbol #travel
🛃  CUSTOMS  #customs #place #sign #symbol #travel
🛄  BAGGAGE CLAIM  #baggage #claim #place #sign #symbol #travel
🛅  LEFT LUGGAGE  #baggage #left_luggage #locker #luggage #place #sign #symbol #travel
⚠  WARNING SIGN  #place #symbol #travel #warning
🚸  CHILDREN CROSSING  #child #crossing #pedestrian #place #sign #symbol #traffic #travel
⛔  NO ENTRY  #entry #forbidden #no #not #prohibited #symbol #traffic #travel
🚫  NO ENTRY SIGN  #entry #forbidden #no #not #prohibited #symbol #travel
🚳  NO BICYCLES  #bicycle #bike #forbidden #no #not #place #prohibited #sign #sport #symbol #travel #vehicle
🚭  NO SMOKING SYMBOL  #forbidden #no #not #prohibited #sign #smoking #symbol #travel
🚯  DO NOT LITTER SYMBOL  #forbidden #litter #no #not #prohibited #sign #symbol #travel
🚱  NON-POTABLE WATER SYMBOL  #drink #forbidden #no #not #potable #prohibited #sign #symbol #travel #water
🚷  NO PEDESTRIANS  #forbidden #no #not #pedestrian #place #prohibited #sign #symbol #travel
📵  NO MOBILE PHONES  #cell #communication #forbidden #mobile #no #not #object #phone #prohibited #symbol #telephone
🔞  NO ONE UNDER EIGHTEEN SYMBOL  #18 #age_restriction #eighteen #forbidden #no #not #prohibited #symbol #underage #word
☢  RADIOACTIVE SIGN  #radioactive #sign #symbol
☣  BIOHAZARD SIGN  #biohazard #sign #symbol
⬆  UPWARDS BLACK ARROW	#arrow #cardinal #direction #north #symbol
↗  NORTH EAST ARROW  #arrow #direction #intercardinal #northeast #symbol
➡  BLACK RIGHTWARDS ARROW  #arrow #cardinal #direction #east #symbol
↘  SOUTH EAST ARROW  #arrow #direction #intercardinal #southeast #symbol
⬇  DOWNWARDS BLACK ARROW  #arrow #cardinal #direction #down #south #symbol
↙  SOUTH WEST ARROW  #arrow #direction #intercardinal #southwest #symbol
⬅  LEFTWARDS BLACK ARROW  #arrow #cardinal #direction #symbol #west
↖  NORTH WEST ARROW  #arrow #direction #intercardinal #northwest #symbol
↕  UP DOWN ARROW  #arrow #symbol
↔  LEFT RIGHT ARROW  #arrow #symbol
↩  LEFTWARDS ARROW WITH HOOK  #arrow #symbol
↪  RIGHTWARDS ARROW WITH HOOK  #arrow #symbol
⤴  ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS  #arrow #symbol
⤵  ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS  #arrow #down #symbol
🔃  CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS	#arrow #clockwise #reload #symbol
🔄  ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS  #anticlockwise #arrow #counterclockwise #symbol #withershins
🔙  BACK WITH LEFTWARDS ARROW ABOVE  #arrow #back #symbol
🔚  END WITH LEFTWARDS ARROW ABOVE  #arrow #end #symbol
🔛  ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE  #arrow #mark #on #symbol
🔜  SOON WITH RIGHTWARDS ARROW ABOVE  #arrow #soon #symbol
🔝  TOP WITH UPWARDS ARROW ABOVE  #arrow #symbol #top #up
🛐  PLACE OF WORSHIP  #place #religion #worship
⚛  ATOM SYMBOL	#atheist #atom #symbol
🕉  OM SYMBOL  #hindu #om #religion #symbol
✡  STAR OF DAVID  #david #jew #jewish #religion #star #symbol
☸  WHEEL OF DHARMA  #buddhist #dharma #religion #symbol #wheel
☯  YIN YANG  #religion #sign #symbol #tao #taoist #yang #yin
✝  LATIN CROSS	#christian #cross #religion #symbol
☦  ORTHODOX CROSS  #christian #cross #religion #symbol
☪  STAR AND CRESCENT  #islam #muslim #religion #symbol
☮  PEACE SYMBOL  #peace #sign #symbol
🕎  MENORAH WITH NINE BRANCHES  #candelabrum #candlestick #menorah #object #place #religion
🔯  SIX POINTED STAR WITH MIDDLE DOT  #fortune #object #star #symbol
♻  BLACK UNIVERSAL RECYCLING SYMBOL  #recycle #sign #symbol
📛  NAME BADGE	#badge #name #object #office
⚜  FLEUR-DE-LIS  #fleur #symbol
🔰  JAPANESE SYMBOL FOR BEGINNER  #beginner #chevron #green #japanese #leaf #object #tool #yellow
🔱  TRIDENT EMBLEM  #anchor #emblem #object #ship #symbol #tool #trident
⭕  HEAVY LARGE CIRCLE  #circle #o #symbol #travel
✅  WHITE HEAVY CHECK MARK  #check #mark #sign #symbol
☑  BALLOT BOX WITH CHECK  #ballot #box #check #sign #symbol
✔  HEAVY CHECK MARK  #check #mark #sign #symbol
✖  HEAVY MULTIPLICATION X  #cancel #multiplication #multiply #sign #symbol #x
❌  CROSS MARK  #cancel #mark #multiplication #multiply #sign #symbol #x
❎  NEGATIVE SQUARED CROSS MARK	#mark #sign #square #symbol
➕  HEAVY PLUS SIGN  #math #plus #sign #symbol
➖  HEAVY MINUS SIGN  #math #minus #sign #symbol
➗  HEAVY DIVISION SIGN	#division #math #sign #symbol
➰  CURLY LOOP  #curl #loop #sign #symbol
➿  DOUBLE CURLY LOOP  #curl #double #loop #sign #symbol
〽  PART ALTERNATION MARK  #mark #part #sign #symbol
✳  EIGHT SPOKED ASTERISK  #asterisk #sign #symbol
✴  EIGHT POINTED BLACK STAR  #sign #star #symbol
❇  SPARKLE  #sign #sparkle #symbol
‼  DOUBLE EXCLAMATION MARK  #bangbang #exclamation #mark #punctuation #symbol #word
⁉  EXCLAMATION QUESTION MARK  #exclamation #interrobang #mark #punctuation #question #symbol #word
❓  BLACK QUESTION MARK ORNAMENT  #mark #punctuation #question #symbol #word
❔  WHITE QUESTION MARK ORNAMENT  #mark #outlined #punctuation #question #symbol #word
❕  WHITE EXCLAMATION MARK ORNAMENT  #exclamation #mark #outlined #punctuation #symbol #word
❗  HEAVY EXCLAMATION MARK SYMBOL  #exclamation #mark #punctuation #symbol #word
〰  WAVY DASH  #dash #punctuation #sound #symbol #wavy
©  COPYRIGHT SIGN  #copyright #symbol #word
®  REGISTERED SIGN  #registered #symbol #word
™  TRADE MARK SIGN  #mark #symbol #tm #trademark #word
♈  ARIES  #aries #ram #symbol #time #zodiac
♉  TAURUS  #bull #ox #symbol #taurus #time #zodiac
♊  GEMINI  #gemini #symbol #time #twins #zodiac
♋  CANCER  #cancer #crab #symbol #time #zodiac
♌  LEO	#leo #lion #symbol #time #zodiac
♍  VIRGO  #maiden #symbol #time #virgin #virgo #zodiac
♎  LIBRA  #balance #justice #libra #scales #symbol #time #zodiac
♏  SCORPIUS  #scorpio #scorpion #scorpius #symbol #time #zodiac
♐  SAGITTARIUS	#archer #sagittarius #symbol #time #zodiac
♑  CAPRICORN  #capricorn #goat #symbol #time #zodiac
♒  AQUARIUS  #aquarius #bearer #symbol #time #water #zodiac
♓  PISCES  #fish #pisces #symbol #time #zodiac
⛎  OPHIUCHUS  #bearer #ophiuchus #serpent #snake #symbol #zodiac
🔀  TWISTED RIGHTWARDS ARROWS  #arrow #crossed #symbol
🔁  CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS  #arrow #clockwise #repeat #symbol
🔂  CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY  #arrow #clockwise #once #symbol
▶  BLACK RIGHT-POINTING TRIANGLE  #arrow #play #right #sound #symbol #triangle
⏩  BLACK RIGHT-POINTING DOUBLE TRIANGLE  #arrow #double #fast #forward #sound #symbol
⏭  BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR  #arrow #next_scene #next_track #sound #symbol #triangle
⏯  BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR  #arrow #pause #play #right #sound #symbol #triangle
◀  BLACK LEFT-POINTING TRIANGLE  #arrow #left #reverse #sound #symbol #triangle
⏪  BLACK LEFT-POINTING DOUBLE TRIANGLE	#arrow #double #rewind #sound #symbol
⏮  BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR  #arrow #previous_scene #previous_track #sound #symbol #triangle
🔼  UP-POINTING SMALL RED TRIANGLE  #arrow #button #red #symbol
⏫  BLACK UP-POINTING DOUBLE TRIANGLE  #arrow #double #sound #symbol
🔽  DOWN-POINTING SMALL RED TRIANGLE  #arrow #button #down #red #symbol
⏬  BLACK DOWN-POINTING DOUBLE TRIANGLE	#arrow #double #down #sound #symbol
⏸  DOUBLE VERTICAL BAR	#bar #double #pause #sound #symbol #vertical
⏹  BLACK SQUARE FOR STOP  #sound #square #stop #symbol
⏺  BLACK CIRCLE FOR RECORD  #circle #record #sound #symbol
⏏  EJECT SYMBOL  #eject #sound #symbol
🎦  CINEMA  #activity #camera #cinema #entertainment #film #movie #object #symbol
🔅  LOW BRIGHTNESS SYMBOL  #brightness #dim #low #sign #symbol
🔆  HIGH BRIGHTNESS SYMBOL  #bright #brightness #sign #symbol
📶  ANTENNA WITH BARS  #antenna #bar #cell #communication #mobile #object #phone #signal #symbol #telephone
📳  VIBRATION MODE  #cell #communication #mobile #mode #object #phone #symbol #telephone #vibration
📴  MOBILE PHONE OFF  #cell #communication #mobile #object #off #phone #symbol #telephone
#  Keycap NUMBER SIGN  #hash #keycap #pound #symbol #word
*  Keycap ASTERISK  #asterisk #keycap #star #symbol
0  Keycap DIGIT ZERO  #0 #keycap #symbol #word #zero
1  Keycap DIGIT ONE  #1 #keycap #one #symbol #word
2  Keycap DIGIT TWO  #2 #keycap #symbol #two #word
3  Keycap DIGIT THREE  #3 #keycap #symbol #three #word
4  Keycap DIGIT FOUR  #4 #four #keycap #symbol #word
5  Keycap DIGIT FIVE  #5 #five #keycap #symbol #word
6  Keycap DIGIT SIX  #6 #keycap #six #symbol #word
7  Keycap DIGIT SEVEN  #7 #keycap #seven #symbol #word
8  Keycap DIGIT EIGHT  #8 #eight #keycap #symbol #word
9  Keycap DIGIT NINE  #9 #keycap #nine #symbol #word
🔟  KEYCAP TEN	#10 #keycap #symbol #ten #word
💯  HUNDRED POINTS SYMBOL  #100 #full #hundred #office #score #symbol
🔠  INPUT SYMBOL FOR LATIN CAPITAL LETTERS  #input #latin #letters #symbol #uppercase #word
🔡  INPUT SYMBOL FOR LATIN SMALL LETTERS  #abcd #input #latin #letters #lowercase #symbol #word
🔢  INPUT SYMBOL FOR NUMBERS  #1234 #input #numbers #symbol #word
🔣  INPUT SYMBOL FOR SYMBOLS  #input #symbol #word
🔤  INPUT SYMBOL FOR LATIN LETTERS  #abc #alphabet #input #latin #letters #symbol #word
🅰  NEGATIVE SQUARED LATIN CAPITAL LETTER A  #a #blood #symbol #word
🆎  NEGATIVE SQUARED AB	#ab #blood #symbol #word
🅱  NEGATIVE SQUARED LATIN CAPITAL LETTER B  #b #blood #symbol #word
🆑  SQUARED CL  #cl #symbol #word
🆒  SQUARED COOL  #cool #symbol #word
🆓  SQUARED FREE  #free #symbol #word
ℹ  INFORMATION SOURCE  #i #information #symbol #word
🆔  SQUARED ID  #id #identity #symbol #word
Ⓜ  CIRCLED LATIN CAPITAL LETTER M  #circle #m #place #symbol #word
🆕  SQUARED NEW	#new #symbol #word
🆖  SQUARED NG  #ng #symbol #word
🅾  NEGATIVE SQUARED LATIN CAPITAL LETTER O  #blood #o #symbol #word
🆗  SQUARED OK  #ok #symbol #word
🅿  NEGATIVE SQUARED LATIN CAPITAL LETTER P  #parking #place #sign #symbol #word
🆘  SQUARED SOS	#help #sos #symbol #word
🆙  SQUARED UP WITH EXCLAMATION MARK  #mark #symbol #up #word
🆚  SQUARED VS  #symbol #versus #vs #word
🈁  SQUARED KATAKANA KOKO  #japanese #symbol #word
🈂  SQUARED KATAKANA SA  #japanese #symbol #word
🈷  SQUARED CJK UNIFIED IDEOGRAPH-6708	#japanese #symbol #word
🈶  SQUARED CJK UNIFIED IDEOGRAPH-6709	#japanese #symbol #word
🈯  SQUARED CJK UNIFIED IDEOGRAPH-6307	#japanese #symbol #word
🉐  CIRCLED IDEOGRAPH ADVANTAGE  #japanese #symbol #word
🈹  SQUARED CJK UNIFIED IDEOGRAPH-5272	#japanese #symbol #word
🈚  SQUARED CJK UNIFIED IDEOGRAPH-7121	#japanese #symbol #word
🈲  SQUARED CJK UNIFIED IDEOGRAPH-7981	#japanese #symbol #word
🉑  CIRCLED IDEOGRAPH ACCEPT  #chinese #symbol #word
🈸  SQUARED CJK UNIFIED IDEOGRAPH-7533	#chinese #symbol #word
🈴  SQUARED CJK UNIFIED IDEOGRAPH-5408	#chinese #symbol #word
🈳  SQUARED CJK UNIFIED IDEOGRAPH-7A7A	#chinese #symbol #word
㊗  CIRCLED IDEOGRAPH CONGRATULATION  #chinese #congratulation #congratulations #ideograph #symbol #word
㊙  CIRCLED IDEOGRAPH SECRET  #chinese #ideograph #secret #symbol #word
🈺  SQUARED CJK UNIFIED IDEOGRAPH-55B6	#chinese #symbol #word
🈵  SQUARED CJK UNIFIED IDEOGRAPH-6E80	#chinese #symbol #word
▪  BLACK SMALL SQUARE  #geometric #sign #square #symbol
▫  WHITE SMALL SQUARE  #geometric #sign #square #symbol
◻  WHITE MEDIUM SQUARE	#geometric #sign #square #symbol
◼  BLACK MEDIUM SQUARE	#geometric #sign #square #symbol
◽  WHITE MEDIUM SMALL SQUARE  #geometric #sign #square #symbol
◾  BLACK MEDIUM SMALL SQUARE  #geometric #sign #square #symbol
⬛  BLACK LARGE SQUARE  #geometric #sign #square #symbol
⬜  WHITE LARGE SQUARE  #geometric #sign #square #symbol
🔶  LARGE ORANGE DIAMOND  #diamond #geometric #orange #sign #symbol
🔷  LARGE BLUE DIAMOND	#blue #diamond #geometric #sign #symbol
🔸  SMALL ORANGE DIAMOND  #diamond #geometric #orange #sign #symbol
🔹  SMALL BLUE DIAMOND	#blue #diamond #geometric #sign #symbol
🔺  UP-POINTING RED TRIANGLE  #geometric #red #sign #symbol
🔻  DOWN-POINTING RED TRIANGLE	#down #geometric #red #sign #symbol
💠  DIAMOND SHAPE WITH A DOT INSIDE  #comic #diamond #geometric #inside #sign #symbol
🔘  RADIO BUTTON  #button #geometric #radio #sign #symbol
🔲  BLACK SQUARE BUTTON  #button #geometric #sign #square #symbol
🔳  WHITE SQUARE BUTTON  #button #geometric #outlined #sign #square #symbol
⚪  MEDIUM WHITE CIRCLE	#circle #geometric #sign #symbol
⚫  MEDIUM BLACK CIRCLE	#circle #geometric #sign #symbol
🔴  LARGE RED CIRCLE  #circle #geometric #red #sign #symbol
🔵  LARGE BLUE CIRCLE  #blue #circle #geometric #sign #symbol
🏁  CHEQUERED FLAG  #checkered #chequered #flag #object #place #racing #sport
🚩  TRIANGULAR FLAG ON POST  #flag #object #place #post #travel
🎌  CROSSED FLAGS  #activity #celebration #cross #crossed #flag #japanese #object
🏴  WAVING BLACK FLAG  #flag #object #waving
🏳  WAVING WHITE FLAG  #flag #object #waving
🇦  Flag for Ascension Island  #ascension #flag #island #other
🇦  Flag for Andorra  #andorra #flag #other
🇦  Flag for United Arab Emirates  #emirates #flag #other #uae #united
🇦  Flag for Afghanistan  #afghanistan #flag #other
🇦  Flag for Antigua & Barbuda	#antigua #barbuda #flag #other
🇦  Flag for Anguilla  #anguilla #flag #other
🇦  Flag for Albania  #albania #flag #other
🇦  Flag for Armenia  #armenia #flag #other
🇦  Flag for Angola  #angola #flag #other
🇦  Flag for Antarctica  #antarctica #flag #other
🇦  Flag for Argentina	#argentina #flag #other
🇦  Flag for American Samoa  #american #flag #other #samoa
🇦  Flag for Austria  #austria #flag #other
🇦  Flag for Australia	#australia #flag #other
🇦  Flag for Aruba  #aruba #flag #other
🇦  Flag for Åland Islands  #flag #other
🇦  Flag for Azerbaijan  #azerbaijan #flag #other
🇧  Flag for Bosnia & Herzegovina  #bosnia #flag #herzegovina #other
🇧  Flag for Barbados  #barbados #flag #other
🇧  Flag for Bangladesh  #bangladesh #flag #other
🇧  Flag for Belgium  #belgium #flag #other
🇧  Flag for Burkina Faso  #burkina_faso #flag #other
🇧  Flag for Bulgaria  #bulgaria #flag #other
🇧  Flag for Bahrain  #bahrain #flag #other
🇧  Flag for Burundi  #burundi #flag #other
🇧  Flag for Benin  #benin #flag #other
🇧  Flag for St. Barthélemy  #barthelemy #barth #flag #other #saint
🇧  Flag for Bermuda  #bermuda #flag #other
🇧  Flag for Brunei  #brunei #darussalam #flag #other
🇧  Flag for Bolivia  #bolivia #flag #other
🇧  Flag for Caribbean Netherlands  #bonaire #caribbean #eustatius #flag #netherlands #other #saba #sint
🇧  Flag for Brazil  #brazil #flag #other
🇧  Flag for Bahamas  #bahamas #flag #other
🇧  Flag for Bhutan  #bhutan #flag #other
🇧  Flag for Bouvet Island  #bouvet #flag #island #other
🇧  Flag for Botswana  #botswana #flag #other
🇧  Flag for Belarus  #belarus #flag #other
🇧  Flag for Belize  #belize #flag #other
🇨  Flag for Canada  #canada #flag #other
🇨  Flag for Cocos Islands  #cocos #flag #island #keeling #other
🇨  Flag for Congo - Kinshasa  #congo #congo #democratic_republic_of_congo #drc #flag #kinshasa #other #republic
🇨  Flag for Central African Republic  #central_african_republic #flag #other #republic
🇨  Flag for Congo - Brazzaville  #brazzaville #congo #congo_republic #congo #flag #other #republic #republic_of_the_congo
🇨  Flag for Switzerland  #flag #other #switzerland
🇨  Flag for Côte d’Ivoire  #cote_ivoire #c #flag #ivory_coast #other
🇨  Flag for Cook Islands  #cook #flag #island #other
🇨  Flag for Chile  #chile #flag #other
🇨  Flag for Cameroon  #cameroon #flag #other
🇨  Flag for China  #china #flag #other
🇨  Flag for Colombia  #colombia #flag #other
🇨  Flag for Clipperton Island	#clipperton #flag #island #other
🇨  Flag for Costa Rica  #costa_rica #flag #other
🇨  Flag for Cuba  #cuba #flag #other
🇨  Flag for Cape Verde  #cabo #cape #flag #other #verde
🇨  Flag for Curaçao  #antilles #curacao #cura #flag #other
🇨  Flag for Christmas Island  #christmas #flag #island #other
🇨  Flag for Cyprus  #cyprus #flag #other
🇨  Flag for Czech Republic  #czech_republic #flag #other
🇩  Flag for Germany  #flag #germany #other
🇩  Flag for Diego Garcia  #diego_garcia #flag #other
🇩  Flag for Djibouti  #djibouti #flag #other
🇩  Flag for Denmark  #denmark #flag #other
🇩  Flag for Dominica  #dominica #flag #other
🇩  Flag for Dominican Republic  #dominican_republic #flag #other
🇩  Flag for Algeria  #algeria #flag #other
🇪  Flag for Ceuta & Melilla  #ceuta #flag #melilla #other
🇪  Flag for Ecuador  #ecuador #flag #other
🇪  Flag for Estonia  #estonia #flag #other
🇪  Flag for Egypt  #egypt #flag #other
🇪  Flag for Western Sahara  #flag #other #sahara #west #western_sahara
🇪  Flag for Eritrea  #eritrea #flag #other
🇪  Flag for Spain  #flag #other #spain
🇪  Flag for Ethiopia  #ethiopia #flag #other
🇪  Flag for European Union  #european_union #flag #other
🇫  Flag for Finland  #finland #flag #other
🇫  Flag for Fiji  #fiji #flag #other
🇫  Flag for Falkland Islands  #falkland #falklands #flag #island #islas #malvinas #other
🇫  Flag for Micronesia  #flag #micronesia #other
🇫  Flag for Faroe Islands  #faroe #flag #island #other
🇫  Flag for France  #flag #france #other
🇬  Flag for Gabon  #flag #gabon #other
🇬  Flag for United Kingdom  #britain #british #cornwall #england #flag #great_britain #ireland #northern_ireland #other #scotland #uk #union_jack #united #united_kingdom #wales
🇬  Flag for Grenada  #flag #grenada #other
🇬  Flag for Georgia  #flag #georgia #other
🇬  Flag for French Guiana  #flag #french #guiana #other
🇬  Flag for Guernsey  #flag #guernsey #other
🇬  Flag for Ghana  #flag #ghana #other
🇬  Flag for Gibraltar	#flag #gibraltar #other
🇬  Flag for Greenland	#flag #greenland #other
🇬  Flag for Gambia  #flag #gambia #other
🇬  Flag for Guinea  #flag #guinea #other
🇬  Flag for Guadeloupe  #flag #guadeloupe #other
🇬  Flag for Equatorial Guinea	#equatorial_guinea #flag #guinea #other
🇬  Flag for Greece  #flag #greece #other
🇬  Flag for South Georgia & South Sandwich Islands  #flag #georgia #island #other #south #south_georgia #south_sandwich
🇬  Flag for Guatemala	#flag #guatemala #other
🇬  Flag for Guam  #flag #guam #other
🇬  Flag for Guinea-Bissau  #bissau #flag #guinea #other
🇬  Flag for Guyana  #flag #guyana #other
🇭  Flag for Hong Kong	#china #flag #hong_kong #other
🇭  Flag for Heard & McDonald Islands  #flag #heard #island #mcdonald #other
🇭  Flag for Honduras  #flag #honduras #other
🇭  Flag for Croatia  #croatia #flag #other
🇭  Flag for Haiti  #flag #haiti #other
🇭  Flag for Hungary  #flag #hungary #other
🇮  Flag for Canary Islands  #canary #flag #island #other
🇮  Flag for Indonesia	#flag #indonesia #other
🇮  Flag for Ireland  #flag #ireland #other
🇮  Flag for Israel  #flag #israel #other
🇮  Flag for Isle of Man  #flag #isle_of_man #other
🇮  Flag for India  #flag #india #other
🇮  Flag for British Indian Ocean Territory  #british #chagos #flag #indian_ocean #island #other
🇮  Flag for Iraq  #flag #iraq #other
🇮  Flag for Iran  #flag #iran #other
🇮  Flag for Iceland  #flag #iceland #other
🇮  Flag for Italy  #flag #italy #other
🇯  Flag for Jersey  #flag #jersey #other
🇯  Flag for Jamaica  #flag #jamaica #other
🇯  Flag for Jordan  #flag #jordan #other
🇯  Flag for Japan  #flag #japan #other
🇰  Flag for Kenya  #flag #kenya #other
🇰  Flag for Kyrgyzstan  #flag #kyrgyzstan #other
🇰  Flag for Cambodia  #cambodia #flag #other
🇰  Flag for Kiribati  #flag #kiribati #other
🇰  Flag for Comoros  #comoros #flag #other
🇰  Flag for St. Kitts & Nevis	#flag #kitts #nevis #other #saint
🇰  Flag for North Korea  #flag #korea #north #north_korea #other
🇰  Flag for South Korea  #flag #korea #other #south #south_korea
🇰  Flag for Kuwait  #flag #kuwait #other
🇰  Flag for Cayman Islands  #cayman #flag #island #other
🇰  Flag for Kazakhstan  #flag #kazakhstan #other
🇱  Flag for Laos  #flag #laos #other
🇱  Flag for Lebanon  #flag #lebanon #other
🇱  Flag for St. Lucia	#flag #lucia #other #saint
🇱  Flag for Liechtenstein  #flag #liechtenstein #other
🇱  Flag for Sri Lanka	#flag #other #sri_lanka
🇱  Flag for Liberia  #flag #liberia #other
🇱  Flag for Lesotho  #flag #lesotho #other
🇱  Flag for Lithuania	#flag #lithuania #other
🇱  Flag for Luxembourg  #flag #luxembourg #other
🇱  Flag for Latvia  #flag #latvia #other
🇱  Flag for Libya  #flag #libya #other
🇲  Flag for Morocco  #flag #morocco #other
🇲  Flag for Monaco  #flag #monaco #other
🇲  Flag for Moldova  #flag #moldova #other
🇲  Flag for Montenegro  #flag #montenegro #other
🇲  Flag for St. Martin  #flag #french #martin #other #saint
🇲  Flag for Madagascar  #flag #madagascar #other
🇲  Flag for Marshall Islands  #flag #island #marshall #other
🇲  Flag for Macedonia	#flag #macedonia #other
🇲  Flag for Mali  #flag #mali #other
🇲  Flag for Myanmar  #burma #flag #myanmar #other
🇲  Flag for Mongolia  #flag #mongolia #other
🇲  Flag for Macau  #china #flag #macao #macau #other
🇲  Flag for Northern Mariana Islands  #flag #island #mariana #north #northern_mariana #other
🇲  Flag for Martinique  #flag #martinique #other
🇲  Flag for Mauritania  #flag #mauritania #other
🇲  Flag for Montserrat  #flag #montserrat #other
🇲  Flag for Malta  #flag #malta #other
🇲  Flag for Mauritius	#flag #mauritius #other
🇲  Flag for Maldives  #flag #maldives #other
🇲  Flag for Malawi  #flag #malawi #other
🇲  Flag for Mexico  #flag #mexico #other
🇲  Flag for Malaysia  #flag #malaysia #other
🇲  Flag for Mozambique  #flag #mozambique #other
🇳  Flag for Namibia  #flag #namibia #other
🇳  Flag for New Caledonia  #flag #new #new_caledonia #other
🇳  Flag for Niger  #flag #niger #other
🇳  Flag for Norfolk Island  #flag #island #norfolk #other
🇳  Flag for Nigeria  #flag #nigeria #other
🇳  Flag for Nicaragua	#flag #nicaragua #other
🇳  Flag for Netherlands  #flag #netherlands #other
🇳  Flag for Norway  #flag #norway #other
🇳  Flag for Nepal  #flag #nepal #other
🇳  Flag for Nauru  #flag #nauru #other
🇳  Flag for Niue  #flag #niue #other
🇳  Flag for New Zealand  #flag #new #new_zealand #other
🇴  Flag for Oman  #flag #oman #other
🇵  Flag for Panama  #flag #other #panama
🇵  Flag for Peru  #flag #other #peru
🇵  Flag for French Polynesia  #flag #french #other #polynesia
🇵  Flag for Papua New Guinea  #flag #guinea #new #other #papua_new_guinea
🇵  Flag for Philippines  #flag #other #philippines
🇵  Flag for Pakistan  #flag #other #pakistan
🇵  Flag for Poland  #flag #other #poland
🇵  Flag for St. Pierre & Miquelon  #flag #miquelon #other #pierre #saint
🇵  Flag for Pitcairn Islands  #flag #island #other #pitcairn
🇵  Flag for Puerto Rico  #flag #other #puerto_rico
🇵  Flag for Palestinian Territories  #flag #other #palestine
🇵  Flag for Portugal  #flag #other #portugal
🇵  Flag for Palau  #flag #other #palau
🇵  Flag for Paraguay  #flag #other #paraguay
🇶  Flag for Qatar  #flag #other #qatar
🇷  Flag for Réunion  #flag #other #reunion #r
🇷  Flag for Romania  #flag #other #romania
🇷  Flag for Serbia  #flag #other #serbia
🇷  Flag for Russia  #flag #other #russia
🇷  Flag for Rwanda  #flag #other #rwanda
🇸  Flag for Saudi Arabia  #flag #other #saudi_arabia
🇸  Flag for Solomon Islands  #flag #island #other #solomon
🇸  Flag for Seychelles  #flag #other #seychelles
🇸  Flag for Sudan  #flag #other #sudan
🇸  Flag for Sweden  #flag #other #sweden
🇸  Flag for Singapore	#flag #other #singapore
🇸  Flag for St. Helena  #flag #helena #other #saint
🇸  Flag for Slovenia  #flag #other #slovenia
🇸  Flag for Svalbard & Jan Mayen  #flag #jan_mayen #other #svalbard
🇸  Flag for Slovakia  #flag #other #slovakia
🇸  Flag for Sierra Leone  #flag #other #sierra_leone
🇸  Flag for San Marino  #flag #other #san_marino
🇸  Flag for Senegal  #flag #other #senegal
🇸  Flag for Somalia  #flag #other #somalia
🇸  Flag for Suriname  #flag #other #suriname
🇸  Flag for South Sudan  #flag #other #south #south_sudan #sudan
🇸  Flag for São Tomé & Príncipe  #flag #other #principe #pr #sao_tome #s
🇸  Flag for El Salvador  #el_salvador #flag #other
🇸  Flag for Sint Maarten  #flag #maarten #other #sint
🇸  Flag for Syria  #flag #other #syria
🇸  Flag for Swaziland	#flag #other #swaziland
🇹  Flag for Tristan da Cunha  #flag #other #tristan_da_cunha
🇹  Flag for Turks & Caicos Islands  #caicos #flag #island #other #turks
🇹  Flag for Chad  #chad #flag #other
🇹  Flag for French Southern Territories  #antarctic #flag #french #other
🇹  Flag for Togo  #flag #other #togo
🇹  Flag for Thailand  #flag #other #thailand
🇹  Flag for Tajikistan  #flag #other #tajikistan
🇹  Flag for Tokelau  #flag #other #tokelau
🇹  Flag for Timor-Leste  #east #east_timor #flag #other #timor
🇹  Flag for Turkmenistan  #flag #other #turkmenistan
🇹  Flag for Tunisia  #flag #other #tunisia
🇹  Flag for Tonga  #flag #other #tonga
🇹  Flag for Turkey  #flag #other #turkey
🇹  Flag for Trinidad & Tobago	#flag #other #tobago #trinidad
🇹  Flag for Tuvalu  #flag #other #tuvalu
🇹  Flag for Taiwan  #china #flag #other #taiwan
🇹  Flag for Tanzania  #flag #other #tanzania
🇺  Flag for Ukraine  #flag #other #ukraine
🇺  Flag for Uganda  #flag #other #uganda
🇺  Flag for U.S. Outlying Islands  #america #flag #island #minor_outlying #other #united #united_states #us #usa
🇺  Flag for United States  #america #flag #other #stars_and_stripes #united #united_states
🇺  Flag for Uruguay  #flag #other #uruguay
🇺  Flag for Uzbekistan  #flag #other #uzbekistan
🇻  Flag for Vatican City  #flag #other #vatican
🇻  Flag for St. Vincent & Grenadines  #flag #grenadines #other #saint #vincent
🇻  Flag for Venezuela	#flag #other #venezuela
🇻  Flag for British Virgin Islands  #british #flag #island #other #virgin
🇻  Flag for U.S. Virgin Islands  #america #american #flag #island #other #united #united_states #us #usa #virgin
🇻  Flag for Vietnam  #flag #other #viet_nam #vietnam
🇻  Flag for Vanuatu  #flag #other #vanuatu
🇼  Flag for Wallis & Futuna  #flag #futuna #other #wallis
🇼  Flag for Samoa  #flag #other #samoa
🇽  Flag for Kosovo  #flag #kosovo #other
🇾  Flag for Yemen  #flag #other #yemen
🇾  Flag for Mayotte  #flag #mayotte #other
🇿  Flag for South Africa  #flag #other #south #south_africa
🇿  Flag for Zambia  #flag #other #zambia
🇿  Flag for Zimbabwe  #flag #other #zimbabwe

