#!/bin/bash

clock() {
    echo $(date +"%H:%M %p ")
}

volume() {
    NOTMUTED=$(amixer -M | head -5 | grep "\[on\]")
    AUDIO=$(amixer -M | head -5 | grep -o -m 1 -E "[[:digit:]]+%")

    if [ -z "$NOTMUTED" ];
    then
        echo " muted "
    else
        case "$AUDIO" in
            0%|[0-9]%) echo " $AUDIO " ;;
            1?%|2?%|3?%) echo " $AUDIO " ;;
            4?%|5?%|6?%) echo " $AUDIO " ;;
            *) echo " $AUDIO " ;;
        esac
    fi
}

battery() {
    battery_status=$(cat /sys/class/power_supply/BAT0/status)
    battery_percent=$(cat /sys/class/power_supply/BAT0/capacity)
    case "$battery_status" in
        Charging) echo " ${battery_percent}% ";;
        Discharging)
            if [ "$battery_percent" -gt 80 ]
            then
                echo " ${battery_percent}% "
            elif [ "$battery_percent" -gt 50 ]
            then
                echo " ${battery_percent}% "
            elif [ "$battery_percent" -gt 16 ]
            then
                echo " ${battery_percent}% "
            else
                echo " ${battery_percent}% "
            fi
            ;;
        Unknown|Full) echo " 100% ";;
    esac
}

while true
do
    xsetroot -name " $(clock)                                                                                                 $(battery)  $(volume)"
    sleep 2
done

