#!/bin/mksh

if [ "$TERM" = "linux" ]; then
    echo -en "\e]P02D333D" #nord background
    echo -en "\e]P82D333D" #darkgrey
    echo -en "\e]P1BF616A" #pink
    echo -en "\e]P9BF616A" #pink
    echo -en "\e]P281A1C1" #lightgreen
    echo -en "\e]PAA3BE8C" #green
    echo -en "\e]P3666666" #brown
    echo -en "\e]PBEBCB8B" #yellow
    echo -en "\e]P481A1C1" #darkblue
    echo -en "\e]PC81A1C1" #blue
    echo -en "\e]P5706c9a" #darkmagenta
    echo -en "\e]PD826ab1" #magenta
    echo -en "\e]P688C0D0" #darkcyan
    echo -en "\e]PED8DEE9" #cyan
    echo -en "\e]P7D8DEE9" #lightgrey
    echo -en "\e]PFD8DEE9" #white
    clear #for background artifacting
fi

bind ^L=clear-screen
umask 077

[ `id -u` = '0' ] && PS1='# >' || PS1='$(pwd | sed "s,^$HOME,~,") $(printf "\033[0;36m$\033[00m")> '
PS2='> '
export PS1 PS2

HISTSIZE=256
HISTFILE=/tmp/.`id -nu`-history

alias ..="cd .."

'!!'() {
	echo "$(history -1 | grep -oP "(?<=\t).*$")"
	$(history -1 | grep -oP "(?<=\t).*$")
}

# ix.io - txt file upload
ix() {
    curl -sF f:1='<-' ix.io < "$*"
}

# iotek - txt file upload
io(){
    curl -sT- https://p.iotek.org < "$*"
}

### uguu - txt/images upload only for 24 hours
uguu () {
    for i in $*; do
        curl -i -F file="@$i" https://uguu.se/api.php?d=upload-tool | grep https
    done
}

fuwa() {
    for i in "$@"; do
        curl -s -F file=@$i} https://fuwa.se/api/upload
    done
}

### mixtape - txt/image upload up to 100MB
mix() {
    for i in "$@"; do
        curl -sf -F files[]=$i https://mixtape.moe/upload.php
    done
}

# anonfile - any file upload up to 10gb (this site is like transfer.sh) - the link is a download link
anon() {
    for i in "$@"; do
        curl -F document=@$i https://anonfiles.cc/api/upload
    done
}

'!g'() {
    oi=$(echo $@ | sed 's/\ /+/')
    torsocks $BROWSERCLI https://google.com/search?q="$oi" -noreferer
}

'!ddg' () {
    oi=$(echo $@ | sed 's/\ /+/')
    torsocks $BROWSERCLI https://duckduckgo.com/?q="$oi" -noreferer
}

#

source "$HOME/.vim/gruvbox_256palette.sh"
#source $HOME/.aliases
[ -f ~/.xprofile ] && source ~/.xprofile

