#! /bin/sh

# Autostart {{{
# Scratchpad terminal: https://www.reddit.com/r/bspwm/comments/85hr4c/making_a_scratchpaddropdown_terminal_in_bspwm/
# I've modified a little bit to open with a tmux session instead of just a terminal
hsetroot -fill ~/Pictures/Landscapes/river-forest.jpg
xsetroot -cursor_name left_ptr
xrdb -load ~/.Xresources
xset +fp $HOME/.fonts/
$HOME/bin/todo-notify
st -c scratchterm -g 80x20 -e vim $HOME/syncthing/markor/Tasks/notes.md
killall -9 sxhkd bar dunst
sxhkd &
dunst &
sleep 1
bar &
notify-send "Notification" "Bspwmrc Loaded"
# }}}
# bspwm config {{{
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X' # Workspace icons
#bspc monitor -d • • • • • • • • • •
bspc config focus_follows_pointer   true
bspc config border_width            0
bspc config window_gap              12                             # Gap size
bspc config normal_border_color     "#528588"                      # border color of normal windows
bspc config focused_border_color    "#dee3e0"                      # border color of focused windows
bspc config presel_feedback_color   "#528588"                      # color of preview new window
bspc config borderless_monocle      true                           # Fullscreen mode do not have a border
bspc config gapless_monocle         true
bspc config split_ratio             0.5
bspc config top_padding             25
bspc config bottom_padding          13
bspc config initial_polarity        second_child

# Rules
bspc rule -a 'Pale moon'     desktop='^2'
bspc rule -a zathura         desktop='^4'   focus=on
bspc rule -a ranger          desktop='^4'   focus=on
bspc rule -a neomutt         desktop='^5'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a weechat         desktop='^7'
bspc rule -a mpv             state=floating center=true
bspc rule -a Sxiv            state=floating center=true
bspc rule -a Screenkey       manage=off
bspc rule -a scratchterm     sticky=on state=floating hidden=on
# }}}
