#! /bin/sh

hsetroot -fill ~/Pictures/Landscapes/river-forest.jpg
xrdb -load $HOME/.Xresources
xmodmap $HOME/.Xmodmap
xset +fp $HOME/.fonts/
$HOME/bin/todo-notify
killall -9 sxhkd dunst
bar 2>/dev/null &
#$HOME/.config/lemonbar/lemonbar.sh
sxhkd &
dunst &
sleep 1
notify-send "Notification" "Bspwmrc Loaded"

bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X'
bspc config focus_follows_pointer   true
bspc config border_width            5
bspc config window_gap              12
bspc config normal_border_color     "#528588"
bspc config focused_border_color    "#dee3e0"
bspc config presel_feedback_color   "#2c3939"
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config split_ratio             0.5
bspc config bottom_padding          33

# Rules
bspc rule -a st              desktop='^1'   state=floating
bspc rule -a 'Pale moon'     desktop='^2'
bspc rule -a TelegramDesktop desktop='^6'   state=floating
bspc rule -a zathura         desktop='^4'   focus=on
bspc rule -a mpv             state=floating center=true
bspc rule -a Sxiv            state=floating center=true
bspc rule -a Screenkey       manage=off
