#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $userresources
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

#xset +fp $HOME/.fonts/

dbus="dbus-launch --sh-syntax --exit-with-session" 
exec redshift &
#setroot -f $HOME/Pictures/Wallpapers/04.jpg

# startx bspwm
# startx dwm
# ...
case $2 in
    bspwm)
        ntpdate a.ntp.br
        exec $dbus bspwm
        ;;
    dwm)
        while true; do
            # Log stderror to a file
            dwm 2> /tmp/dwm.log
            # No error logging
            #dwm >/dev/null 2>&1
        done
        ;;
    *) exec $dbus bspwm ;;
esac
